### ISSUE TITLE
default-nar-compile gcc failed with return code 1

### ISSUE THREAD

**Issue by afarguellesd** [tada/pljava#104]
Hi.

I am trying to build pljava 1.5.0. I am getting the error of the subject: This is the installation environment:

- SO: CentOS Linux 7
- Postgresql: 9.4.7
- Postgresql installed packages:
```
postgresql94-9.4.7-1PGDG.rhel7.x86_64
postgresql94-jdbc-javadoc-9.4.1207-2.rhel7.noarch
postgresql94-debuginfo-9.4.7-1PGDG.rhel7.x86_64
postgresql94-docs-9.4.7-1PGDG.rhel7.x86_64
postgresql94-libs-9.4.7-1PGDG.rhel7.x86_64
postgresql94-contrib-9.4.7-1PGDG.rhel7.x86_64
postgresql94-server-9.4.7-1PGDG.rhel7.x86_64
postgresql94-jdbc-9.4.1207-2.rhel7.noarch
postgresql94-odbc-09.05.0200-1PGDG.rhel7.x86_64
postgresql94-tcl-2.1.1-1.rhel7.x86_64
postgresql94-plperl-9.4.7-1PGDG.rhel7.x86_64
postgresql94-tcl-debuginfo-2.1.1-1.rhel7.x86_64
postgresql94-plpython-9.4.7-1PGDG.rhel7.x86_64
postgresql94-odbc-debuginfo-09.03.0400-1PGDG.rhel7.x86_64
postgresql94-test-9.4.7-1PGDG.rhel7.x86_64
postgresql94-pltcl-9.4.7-1PGDG.rhel7.x86_64
postgresql94-python-debuginfo-4.2-1PGDG.rhel7.x86_64
postgresql94-python-4.2-1PGDG.rhel7.x86_64
postgresql94-devel-9.4.7-1PGDG.rhel7.x86_64
```

- gcc and gcc-c++ are installed.

```
gcc-objc-4.8.5-4.el7.x86_64
gcc-plugin-devel-4.8.5-4.el7.x86_64
gcc-4.8.5-4.el7.x86_64
libgcc-4.8.5-4.el7.x86_64
gcc-gfortran-4.8.5-4.el7.x86_64
gcc-go-4.8.5-4.el7.x86_64
gcc-c++-4.8.5-4.el7.x86_64
gcc-gnat-4.8.5-4.el7.x86_64
```

- Maven version:

```
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T11:41:47-05:00)
Maven home: /opt/apache-maven-3.3.9
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/java/jdk1.7.0_79/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-327.el7.x86_64", arch: "amd64", family: "unix"
```

- Java version:

```
javac 1.7.0_79
```

I am attaching maven output with debug messages. I have already tried to change nar-maven plugin version with the same results.

I appreciate any hint you guys could give me with this.

Regards
[pljava_log.log.txt](https://github.com/tada/pljava/files/249748/pljava_log.log.txt)

**Comment by jcflack** [comment]
Hi,

The development package for OpenSSL, `openssl-devel`, is a prerequisite if PostgreSQL was built with openssl. You seem not to have it installed; the one line in your log that contains 'fatal error:' is line 5709, showing that openssl/ssl.h cannot be found.

If you look over the 'troubleshooting the build' section on the build page, you'll see a tip for disabling the many nuisance sign-conversion warnings, making it easier to see actual error messages.

Regards,
-Chap

**Comment by afarguellesd** [comment]
Hi,

After installing openssl-devel the issue was solved. I was confused because I did not check postgresql dependencies before building pljava.

Regards,

Andrés
