### ISSUE TITLE
Unable to build PlJava jar using Maven it is failed 

### ISSUE THREAD

**Issue by RamakrishnaAddanki** [tada/pljava#107]
Hi guys,

I have downloaded the zip file of pljava and tried to build it.but it is failed due to the following error can any one please help in resolving this issue.

Please Find Screenshot for more info........

Error info:
![pl_java_build_failure_issue](https://cloud.githubusercontent.com/assets/14921776/16183280/aeed879a-36cd-11e6-9302-adc00d8084b2.png)

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project pljava-api: Fatal error compiling: tools.jar not found: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.71-1.b15.el6_7.x86_64/jre/../lib/tools.jar -> 

Thanks 
Ramakrishna.A

**Comment by RamakrishnaAddanki** [comment]
resolved

**Comment by slimatic** [comment]
How was it resolved? I have similar issue.

**Comment by jcflack** [comment]
The person making the original report just resolved it without comment (I suppose after finding the problem), but, reading between the lines, my guess would be that perhaps a JRE was installed, but a full JDK was not. (Without a JRE, Maven itself would not have run, and with a JDK present, the javac compiler plugin should have worked.)

I see with Google that there might have been one or more early Java 8 release(s) with tools.jar simply missing. That would also cause the issue. In that case, it ought to be resolved by updating to a later Java release.

-Chap
