### ISSUE TITLE
Aggregate State / threading

### ISSUE THREAD

**Issue by fab1an** [tada/pljava#113]
When writing a custom aggregate function, is it necessary to pass the state between the iterations like usual?
I think one could have the state as static variable in Java, since the JVM-process is single-threaded anyway.

Any thought on this?

**Comment by jcflack** [comment]
PostgreSQL will be remembering and passing the state in each call anyway, so it seems safest to use it. I would be leery of keeping it as a static in Java; the JVM may be single-threaded, but if PostgreSQL is evaluating a query that happens to involve the same aggregate applied to columns, for example, it may be calling the aggregate function alternately with the two different states.

**Comment by fab1an** [comment]
That makes sense, thank you.
