### ISSUE TITLE
doc/api clarification on ResultSetProvider/currentRow

### ISSUE THREAD

**Issue by fab1an** [tada/pljava#115]
Will `assignRowValues` be called with `currentRow` set first to 0, incrementing one by one to `n`, or is it possible that the rows are requested randomly?

**Comment by jcflack** [comment]
Good question! I see that PL/Java's [apidoc][rsp] does say "First call will have row number 0", so the only thing left vague is whether the following row numbers successively increment.

[rsp]: https://tada.github.io/pljava/pljava-api/apidocs/index.html?org/postgresql/pljava/ResultSetProvider.html

For that, the real answer is that the collection of result rows is being driven by PostgreSQL itself, and that value comes from `call_cntr` in PostgreSQL's [`struct FuncCallContext`][sfcc], and indeed the documentation there says it starts at 0 and is "incremented for you every time".

[sfcc]: https://www.postgresql.org/docs/current/static/xfunc-c.html#XFUNC-C-RETURN-SET

**Comment by jcflack** [comment]
Fixed on the wiki, and fix to Javadoc pushed, will appear in next 1.5.x release.
