### ISSUE TITLE
Upgrade failure from 9.5 to 9.6

### ISSUE THREAD

**Issue by darkixion** [tada/pljava#117]
In EDB Postgres, I'm seeing a failure during the upgrade process from 9.5 to 9.6.  I'm attempting to recreate it in the community version too (although currently having issues building pljava).

> ERROR:  pg_class heap OID value not set when in binary upgrade mode
> CONTEXT:  SQL statement "CREATE TABLE sqlj.jar_repository( jarId SERIAL PRIMARY KEY, jarName VARCHAR(100) UNIQUE NOT NULL, jarOrigin VARCHAR(500) NOT NULL, jarOwner NAME NOT NULL, jarManifest TEXT )"

Prior to 9.6, pg_dump output was supposed to contain an annotation to cause OIDs to be set correctly when --binary-upgrade was being used.  In 9.6, Bruce Momjian introduced [a change that checks OIDs][a7ae1], but it seems that pl/Java decides to make changes to the database.  It shouldn't be creating the table, it should let the dump and restore process take care of this.

Is there a step that needs to be removed so that it completes this successfully?

*edited by jcflack to link to the change in question, which actually appeared in 9.5.*

[a7ae1]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=blobdiff;f=src/backend/catalog/heap.c;h=c346edac93be55889e8fe18398579be551ce0f5f;hp=33eef9f1caffcfbcd178140047d1ef64abb5145c;hb=a7ae1dcf4939cf643c5abe8dd673e4b87a6efd42;hpb=73fe87503f23144a27f0bdecc55587deb5aa425f

**Comment by jcflack** [comment]
There could well be. I may need to look into whether `pg_upgrade` sets some kind of state that an extension can check when it is loaded to recognize it's in the midst of a `pg_upgrade`.

**Comment by jcflack** [comment]
... and, I'm told there is a global `IsBinaryUpgrade` that can be checked for exactly that purpose.

**Comment by jcflack** [comment]
Closing with release of 1.5.1.
