### ISSUE TITLE
Provide database migration

### ISSUE THREAD

**Issue by thallgren** [tada/pljava#12]
We need a mechanism whereby we can add database migration scripts. Issues like #10 makes changes to the database that are not backward compatible and any environment that wishes to upgrade must have an easy path forward.

**Comment by jcflack** [comment]
As has been mentioned on pljava-dev (but not yet here), starting in PG 9.1 if we provide "extension" packaging and the necessary update scripts, `ALTER EXTENSION UPDATE` will do this for us.
