### ISSUE TITLE
i have 10 tables in schema icmdb2admin each table have one column named pdfname i need to update the values in the pdfname column with L1.pdfname.V1 of all tables in one loop query 

### ISSUE THREAD

**Issue by sarathmv** [tada/pljava#131]
DO
$$
DECLARE
    i record;
BEGIN
    FOR i IN SELECT 'icmdb2admin.' || tablename as tbp  
             FROM pg_tables 
             WHERE schemaname = 'icmdb2admin' 
               and tablename <> 'department_master' 
               and tablename <> 'year'
               and tablename <> 'user_login' 
               and tablename <> 'filetype'  
               
 LOOP 
     EXECUTE  UPDATE "i.tbp" SET "pdfname" = 'L1.'|| pdfname || '.V1'; 
END LOOP;
END;
$$;

but it was showing error 
ERROR:  syntax error at or near "SET"
LINE 15:      EXECUTE  UPDATE "i.tbp" SET "pdfname" = 'L1.'|| pdfname...
                                      ^

********** Error **********

ERROR: syntax error at or near "SET"
SQL state: 42601
Character: 41

**Comment by jcflack** [comment]
Hello,

Does your issue have anything to do with PL/Java (functions written in the Java language and stored on the backend)?

**Comment by jcflack** [comment]
Closed as homework question unrelated to PL/Java.
