### ISSUE TITLE
pljava using wrong Java VM

### ISSUE THREAD

**Issue by agsp159** [tada/pljava#133]
pljava is not using the Java version which has been configured.

To verify, which Java version is used by pljava I have created this function
`CREATE FUNCTION java_getproperty(VARCHAR) RETURNS VARCHAR2 AS 'java.lang.System.getProperty' LANGUAGE java;`
`select java_getproperty('java.version')`
returns 1.6.0_41

This Java version is installed on the server ("Red Hat Enterprise Linux Server" VERSION="7.3 (Maipo)") in
/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64.
But this has not been configured to be used by pljava.

In the environment:
JAVA_HOME=/opt/jdk1.8.0_91
java -version returns 
Picked up JAVA_TOOL_OPTIONS: -Xss2m <-- important, without this setting create extension pljava crashes
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

In postgresql.conf:
pljava.classpath = '/opt/app/edb/as9.6/share/pljava/pljava-1.5.0.jar'
pljava.libjvm_location = '/opt/jdk1.8.0_91/jre/lib/amd64/server/libjvm.so'

So I would expect that pljava uses Java 1.8.0_91.

How can I configure pljava to use the correct Java version?

Any help is really appreciated.

**Comment by jcflack** [comment]
Hi,

Just to rule out that feeling of slowly going insane, could you try something like:

    postgres=# \c
    postgres=# set log_min_messages to debug1;
    postgres=# set client_min_messages to debug1;
    postgres=# select sqlj.get_classpath('public');
    postgres=# select name, source, setting from pg_settings where name like 'pljava.%';

and report what shows up?

**Comment by agsp159** [comment]
pg_settings showed
pljava.libjvm_location	configuration file  /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/jre/lib/amd64/server/libjvm.so
and this forced me to look again into the postgresql.conf file
and there I found
#pljava.libjvm_location = '/opt/jdk1.8.0_91/jre/lib/amd64/server/libjvm.so'
pljava.libjvm_location = '/usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64/jre/lib/amd64/server/libjvm.so' 

I really don't know who modified the configuration file.

After path correction and db restart everything is fine.

Thank you very much.
