### ISSUE TITLE
PostgreSQL 10:  SPI function SPI_modifytuple failed with error SPI_ERROR_UNCONNECTED

### ISSUE THREAD

**Issue by pmichalek** [tada/pljava#134]
Hi,
after upgrade to PosgreSQL 10.1 some triggers stopped working. I have isolated a test case, see bellow. Any help appreciated. Thank you. Petr

PostgreSQL 10.1 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2), 64-bit
Oracle Java 1.8.0.152
PL/JAVA branch trackpg/REL1_5_STABLE/pg10

**DDL:**
CREATE TABLE public.test(
  id bigserial NOT NULL,
  t1 timestamp without time zone,
  t1seq integer,
  CONSTRAINT pk_test PRIMARY KEY (id)
);
ALTER TABLE public.test OWNER TO postgres;
GRANT ALL ON TABLE public.test TO postgres;
CREATE TRIGGER test0 BEFORE INSERT OR UPDATE OR DELETE ON public.test FOR EACH ROW EXECUTE PROCEDURE public.test();

**Java Trigger**

import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;

import org.postgresql.pljava.TriggerData;
import org.postgresql.pljava.annotation.Function;
import org.postgresql.pljava.annotation.Trigger;
import org.postgresql.pljava.annotation.Trigger.Called;
import org.postgresql.pljava.annotation.Trigger.Event;
import org.postgresql.pljava.annotation.Trigger.Scope;

public final class TriggerTestCase  {
    @Function(schema = "public", name = "test", triggers = //
    @Trigger(called = Called.BEFORE, scope = Scope.ROW, events = { Event.INSERT, Event.UPDATE, Event.DELETE }, schema = "public", table = "test", name = "test0"))
    public static void triggerBefore(TriggerData td) throws SQLException {

        if (td.isFiredByInsert()) {
            ResultSet trs = td.getNew();
            trs.updateTimestamp("t1", new Timestamp(System.currentTimeMillis()));
        }

    }
}

**SQL Commans:**
insert into test (t1seq) values (1);
insert into test (t1seq) values (2); -- Calling command more than once, returns an exception

** SQL Result **
ERROR: java.sql.SQLException: SPI function SPI_modifytuple failed with error SPI_ERROR_UNCONNECTED
SQL State: XX000

**Comment by pmichalek** [comment]
Hi, 
please, is anybody able to confirm this issue? 

Thanks in advance

**Comment by jcflack** [comment]
I'm sorry, haven't had a chance yet. Will try later today. -Chap

**Comment by jcflack** [comment]
Ok, I can reproduce it, in PostgreSQL 10.1 and PL/Java 1.5.1-BETA1 (that is the most current actual release at the moment, and it includes the trackpg/REL1_5_STABLE/pg10 branch you report building from). I do encourage building from a released version (the ALTER EXTENSION UPDATE machinery won't quite know what to do otherwise).

Do I understand correctly that the same code works for you in older PostgreSQL versions?

Your Java test case did not quite compile (the lowercase `@function` and `@trigger` were the issue). I've taken the liberty of fixing those and adding an `@SQLAction` so the test is self-contained without needing a separate bunch of DDL. So, here's the test case as I'm using it:

    import java.sql.ResultSet;
    import java.sql.SQLException;
    import java.sql.Timestamp;
    
    import org.postgresql.pljava.TriggerData;
    import org.postgresql.pljava.annotation.Function;
    import org.postgresql.pljava.annotation.SQLAction;
    import org.postgresql.pljava.annotation.Trigger;
    import org.postgresql.pljava.annotation.Trigger.Called;
    import org.postgresql.pljava.annotation.Trigger.Event;
    import org.postgresql.pljava.annotation.Trigger.Scope;
    
    @SQLAction(provides="test table",
    	remove="DROP TABLE public.test",
    	install={
    		"CREATE TABLE public.test(" +
    		"    id bigserial NOT NULL," +
    		"    t1 timestamp without time zone," +
    		"    t1seq integer," +
    		"    CONSTRAINT pk_test PRIMARY KEY (id)" +
    		")"
    	}
    )
    public final class TriggerTestCase {
    @Function(schema = "public", name = "test", requires="test table", triggers = //
    @Trigger(called = Called.BEFORE,
    	scope = Scope.ROW,
    	events = { Event.INSERT, Event.UPDATE, Event.DELETE },
    	schema = "public", table = "test", name = "test0"))
    
    	public static void triggerBefore(TriggerData td) throws SQLException {
    
        	if (td.isFiredByInsert()) {
            	ResultSet trs = td.getNew();
            	trs.updateTimestamp("t1",new Timestamp(System.currentTimeMillis()));
        	}
    	}
    }

I'll see what I can learn about why it is failing.

-Chap

**Comment by jcflack** [comment]
Changed in PostgreSQL 10:

[Simplify code by getting rid of SPI_push, SPI_pop, SPI_restore_connection.][pgcommit]

The change means that several `SPI` functions now must only be called when connected:

* SPI_copytuple
* SPI_returntuple
* SPI_modifytuple
* SPI_palloc
* SPI_datumTransfer
* spi_dest_startup
* spi_printtup

`SPI_modifytuple` is the only one used in PL/Java, and only in the one place. Should be straightforward to fix.

[pgcommit]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=1833f1a1c3b0e12b3ea40d49bf11898eedae5248

**Comment by jcflack** [comment]
Hello,

Could you please retry your test case in a build from the `bug/REL1_5_STABLE/issue134` branch?

-Chap

**Comment by pmichalek** [comment]
Hi,
is seems to be OK.
Petr

**Comment by jcflack** [comment]
Closing with release of PL/Java 1.5.1 supporting PostgreSQL 10 and 11 (back to 8.2).
