### ISSUE TITLE
SPIConnection prepareStatement doesn't recognize all parameters when SQL combines single and double quotes 

### ISSUE THREAD

**Issue by pmichalek** [tada/pljava#136]
Hi,

SPIConnection prepareStatement doesn't recognize all parameters when SQL combines single and double quotes. For example:

**UPDATE public.abc SET f1=?, f=?,f3=ARRAY['{"id":1,"a":1,"b":2}']::jsonb[],f4=? WHERE id=?**

is prepared as:

**UPDATE public.abc SET f1=$1, f=$2,f3=ARRAY['{"id":1,"a":1,"b":2}']::jsonb[],f4=? WHERE id=?**

1. Suggested patch is attached.
2. Is possible update array like **pstmt.setObject(...)** ?

Thank you for all your work!
Best regards
[SPIConnection.patch.txt](https://github.com/tada/pljava/files/1693416/SPIConnection.patch.txt)

**Comment by jcflack** [comment]
Closing with release of 1.5.1.
