### ISSUE TITLE
java 8 date/time api

### ISSUE THREAD

**Issue by ghostello** [tada/pljava#137]
At the moment pl/java doesn't support java LocalDateTime/LocalDate in functions.
Do your plan to support java 8 time api in future?
or mb exist some workaround for using LocalDateTime/LocalDate?

**Comment by jcflack** [comment]
Hi,

Can you describe the specific support you would like to see? As described in [this email][three10], there should already be new `valueOf(Local...)` and `toLocal...(...)` methods on the `java.sql` time/date/timestamp objects, which should allow you to use your preferred API in most cases, if with a slight cost of double-conversion.

The ability to pass the `Local...` classes directly to `setObject`/`getObject` is missing, yes. Is that what you are requesting? I see we are behind client PGJDBC, which [has that already][pgj]. That's not surprising, as PL/Java's internal JDBC driver was forked from the client one, but a _long_ time ago.

I might be able to add it without too much trouble though.

[three10]: http://mail.openjdk.java.net/pipermail/jdbc-spec-discuss/2012-December/000010.html
[pgj]: https://jdbc.postgresql.org/documentation/head/8-date-time.html

**Comment by ghostello** [comment]
Hi,
At the moment we use your extension for running some specific function on postgres side. 
For example split date on specific pieces, like fiscal year, fiscal day and e.g.

At the moment everything works well. But we would like to rewrite our functions on new java date/time api for avoiding conversation from java.sql.timestamp to java.time.LocalDateTime. 

it would be very cool if you add support for this.

Thx

**Comment by ghostello** [comment]
Hello, 
Is any news about support  java 8 date/time api?

Thx.

**Comment by jcflack** [comment]
Thank you for the ping. I have looked at the issue, but I won't be able to do any implementation this week. I will return to it.

-Chap

**Comment by jcflack** [comment]
This support has been merged in REL1_5_STABLE and will appear in PL/Java 1.5.1-BETA2.
