### ISSUE TITLE
unknown error 126 - pljava instalation

### ISSUE THREAD

**Issue by greimer** [tada/pljava#14]
Hello. 

I get an error:
ERROR:  no se pudo cargar la biblioteca «C:/Program Files/PostgreSQL/9.2/lib/pljava.dll»: unknown error 126
 
Has anybody else seen this error?

My setup:
Windows 7 Pro;PostgreSQL 9.2.4, compiled by Visual C++ build 1600, 64-bit;
java version "1.7.0_17"

JAVA_HOME = "C:\Program Files\Java\jre7"

PATH = %JRE_HOME%\bin;%JRE_HOME%\bin\client

**Comment by jcflack** [comment]
Not sure why only "unknown error" was shown, but 126 appears to be [ERROR_MOD_NOT_FOUND][].

That suggests the OP had a problem with getting the DLL into the right place, or getting the path correctly pointed at it, which is a common hurdle, and I hope the OP eventually overcame it.

Closing.

[ERROR_MOD_NOT_FOUND]: https://msdn.microsoft.com/en-us/library/windows/desktop/ms681382%28v=vs.85%29.aspx#ERROR_MOD_NOT_FOUND
