### ISSUE TITLE
Installing pl/java on Postgresql 10 - build not ended

### ISSUE THREAD

**Issue by Jul999** [tada/pljava#148]
When I try to build the project with mvn -X clean install I get the following log message without errors but never ended- may You help me.
Thanks 

Setting project property: MSVC_RINT -> msvc.rint
Property "PGSQL_VER_CLASSIFIER" has not been set
[propertyfile] Creating new property file: /opt/postgresql/pljava/pljava-so/target/pgsql.properties
      [ant] Exiting /opt/postgresql/pljava/pljava-so/build.xml.
[INFO] Executed tasks
[INFO] 
[INFO] --- properties-maven-plugin:1.0-alpha-2:read-project-properties (default) @ pljava-so ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=284771, ConflictMarker.markTime=208833, ConflictMarker.nodeCount=31, ConflictIdSorter.graphTime=126125, ConflictIdSorter.topsortTime=116394, ConflictIdSorter.conflictIdCount=14, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2057018, ConflictResolver.conflictItemCount=31, DefaultDependencyCollector.collectTime=25357265, DefaultDependencyCollector.transformTime=2930958}
[DEBUG] org.codehaus.mojo:properties-maven-plugin:jar:1.0-alpha-2:
[DEBUG]    org.apache.maven:maven-model:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-plugin-api:jar:2.0.6:compile
[DEBUG]    org.apache.maven:maven-project:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-settings:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-profile:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-artifact-manager:jar:2.0.6:compile
[DEBUG]          org.apache.maven:maven-repository-metadata:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-plugin-registry:jar:2.0.6:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:2.0.6:compile
[DEBUG]       org.codehaus.plexus:plexus-container-default:jar:1.0-alpha-9-stable-1:compile
[DEBUG]          junit:junit:jar:3.8.2:test
[DEBUG]          classworlds:classworlds:jar:1.1-alpha-2:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:1.5.6:compile
[DEBUG] Created new class realm plugin>org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2
[DEBUG] Importing foreign packages into class realm plugin>org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2
[DEBUG]   Imported:  < project>org.postgresql:pljava-so:1.6.0-SNAPSHOT
[DEBUG] Populating class realm plugin>org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2
[DEBUG]   Included: org.codehaus.mojo:properties-maven-plugin:jar:1.0-alpha-2
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.5.6
[DEBUG] Configuring mojo org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2:read-project-properties from plugin realm ClassRealm[plugin>org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2, parent: sun.misc.Launcher$AppClassLoader@5c647e05]
[DEBUG] Configuring mojo 'org.codehaus.mojo:properties-maven-plugin:1.0-alpha-2:read-project-properties' with basic configurator -->
[DEBUG]   (f) files = [/opt/postgresql/pljava/pljava-so/target/pgsql.properties]
[DEBUG]   (f) project = MavenProject: org.postgresql:pljava-so:1.6.0-SNAPSHOT @ /opt/postgresql/pljava/pljava-so/pom.xml
[DEBUG]   (f) quiet = false
[DEBUG] -- end configuration --
[DEBUG] Loading property file: /opt/postgresql/pljava/pljava-so/target/pgsql.properties

**Comment by jcflack** [comment]
Hi,

I have not seen that happen before, but I notice that you are trying to build an unreleased snapshot from master. If you are running PG 10, the changes for that are only in 1.5.1-BETA1 so far; you can find that on the [releases](https://github.com/tada/pljava/releases) page.

Please try that and see if the same thing happens. Also, please identify your OS.

Thanks!
-Chap

**Comment by Jul999** [comment]
Thanks Chap! .. actually using the pljava version suggested by you on os linux debian 8, with postgresql 10.3 everything works perfectly. Thanks again and congratulations for the quick support!

Jul

**Comment by jcflack** [comment]
Thanks for following up! I'll close this.

-Chap
