### ISSUE TITLE
Missing type mapping for Java return byte[]

### ISSUE THREAD

**Issue by henuahinge** [tada/pljava#157]
Hi,

i tried to execute a Java function like

@Function
public static byte[] encrypt_rsa(String message, byte[] public_key){...}

but if i start maven with 'mvn clean package' i get the error: 'No known mapping to an SQL type'.
I searched the wiki and there it says that pl/java would map byte[] to bytea (https://github.com/tada/pljava/wiki/Default-type-mapping).

Do you know any workaround for this? I relly need this to work (somehow) for my master thesis :/

**Comment by jcflack** [comment]
This surprises me, and I'll see if I can replicate it, but as far as a workaround, you more or less always have an "escape hatch" using annotations explicitly, as in:

    @Function(type = "bytea")
    public static byte[] encrypt_rsa(String message, byte[] public_key){...}

if it was failing to map the return type, or

    @Function
    public static byte[] encrypt_rsa(String message, @SQLType("bytea") byte[] public_key){...}

if it was failing to map the parameter type. Of course, you can do both, if that's what it needs to compile.

Please report back on which annotation(s) you needed to add for it to successfully compile, and the PL/Java version.

**Comment by henuahinge** [comment]
First: Thank you for your fast answer! :)

I made a fast little test (i will test in detail tomorrow).
This time i didn't get any maven errors, so i think everything is fine now.

I had to use both annotations:
` @Function(type = "bytea")`
`    public static byte[] test (@SQLType("bytea") byte[] key){....}`

I am using version 1.5.0 (i used the branch 'REL1_5_STABLE' to install pljava with maven).

**Comment by jcflack** [comment]
I'm glad that worked for you. I'll look into why you needed to do that. :)

By the way, if you build from the branch head `REL1_5_STABLE`, you're building a moving snapshot (on the way to what will be 1.5.1-BETA2 in the near future). You can build from one of the announced release tags (`V1_5_1b1` is the latest at the moment) to have an exact released version. Unreleased snapshots may complicate your life later if you want to do `ALTER EXTENSION ... UPDATE`.

**Comment by jcflack** [comment]
Thank you for reporting this issue. Pull request #158 corrects it (and also eliminates a long-standing mysterious warning that hadn't been pursued, as it had seemed benign with no related problem reports). The patch can be expected in 1.5.1-BETA2, and you will be able to remove the explicit type annotations you added as workarounds.

**Comment by jcflack** [comment]
The fix for this issue is included in the PL/Java 1.5.1-BETA2 release made today.
https://github.com/tada/pljava/releases/tag/V1_5_1b2

**Comment by jcflack** [comment]
Closing with release of 1.5.1.
