### ISSUE TITLE
Update documentation with respect to new Maven build

### ISSUE THREAD

**Issue by thallgren** [tada/pljava#18]
The Wiki documentation for the build https://github.com/tada/pljava/wiki/Building-pl-java is outdated and describes the old makefile based build.

**Comment by jcflack** [comment]
Thanks to Bear Giles, there now is (some) documentation on the Maven build, on the wiki in [Building PL/Java][build]. There is lots of room for fleshing it out, but I think this issue can be closed.

[build]: https://github.com/tada/pljava/wiki/Building-pl-java
