### ISSUE TITLE
java.sql.SQLException: I/O exception reading jar file (Access is denied)

### ISSUE THREAD

**Issue by izuku-franck1555** [tada/pljava#198]
Hello. I just converted a .java program to .class, and then to .java. But once I want to add it to the referential I get this error. I went into administrator mode but it's still the same result. A suggestion please?
![capture](https://user-images.githubusercontent.com/43177617/47537848-0be9eb00-d8c0-11e8-886f-cc6adf3b9c6d.PNG)

**Comment by adriens** [comment]
First, why not trying this :  `/Users/user/Desktop/Maths.jar` ?

**Comment by izuku-franck1555** [comment]
No reason. I did not think about it. But in the screen we see that the .jar file is prohibited. Anyway I try. Another suggestion please?

**Comment by izuku-franck1555** [comment]
Same result !
![capture](https://user-images.githubusercontent.com/43177617/47538182-05f50980-d8c2-11e8-9f16-19aa6b7a25ba.PNG)

**Comment by jcflack** [comment]
I am not especially knowledgeable about how permissions work in Windows. However, one thing to remember is that the PostgreSQL backend is often running as a different identity (for example, `postgres`) than the person running the client. The file in this case has to be readable by the identity of the PostgreSQL backend. Have you tried looking at the Windows properties of the file to see what permissions are set on it?

What happens if you try to load a known-nonexistent jar (say, `\Users\user\Desktop\xyzzy.jar`)? Same error, or different?

**Comment by izuku-franck1555** [comment]
Hello @jcflack . It is a different error.
![capture](https://user-images.githubusercontent.com/43177617/47538471-73556a00-d8c3-11e8-8c08-0606e56ce593.PNG)

**Comment by adriens** [comment]
Also, could give a try to run your shell with `Admin` privileges ?

**Comment by izuku-franck1555** [comment]
That the permissions of Maths.jar
![capture](https://user-images.githubusercontent.com/43177617/47538527-c5968b00-d8c3-11e8-8d37-f0a666b0ecf5.PNG)

**Comment by izuku-franck1555** [comment]
Yes @adriens . I trying.

**Comment by izuku-franck1555** [comment]
![capture](https://user-images.githubusercontent.com/43177617/47538727-cda2fa80-d8c4-11e8-8bfa-32d49e331cda.PNG)

**Comment by jcflack** [comment]
Perhaps you attached a different screenshot than you intended, for the test using a known-wrong file name? The screenshot you posted showed the original file name (and the same Access is denied error).

Note that running your client (`psql`) session as admin, or not, may have no effect on the identity of the PostgreSQL backend. In this case, it is the backend that needs to read the file.

**Comment by izuku-franck1555** [comment]
And what do you suggest to me? It's a duty for tomorrow. I tried everything but nothing works. I went to convert the .java to .jar in my ubuntu partition. I will try to see if it still displays the same error. If so it would mean that psql is not allowed to read a file in my office.

**Comment by izuku-franck1555** [comment]
And the strangest thing is that my friends with whom I installed pl / java as you showed me have the same problem.

**Comment by izuku-franck1555** [comment]
I took a good initiative in doing it. It finally worked.
![capture](https://user-images.githubusercontent.com/43177617/47539525-c847af00-d8c8-11e8-8a0e-a126906a8f19.PNG)

**Comment by izuku-franck1555** [comment]
Thanks to @adriens  and you for your super quick answers. Github is really great !!! :)

**Comment by adriens** [comment]
Github ...and the project community of couse :clap: Happy to have contributed @izuku-franck1555 :+1:
