### ISSUE TITLE
pljava-api artificat not found in public maven repository

### ISSUE THREAD

**Issue by pedroteixeira** [tada/pljava#204]
Hi, is the artifact org.postgresql:pljava-api:1.5.2 supposed to be published at the public maven repository?
https://repo.maven.apache.org/maven2/org/postgresql/

**Comment by jcflack** [comment]
Hi,

I would love to have it available there at some future point, but the necessary arrangements have not been made yet (including with the other project that owns the `org.postgresql` Maven coordinates, and how to have the artifact verifiably built and deployed).

So at present, regrettably, the answer is 'no'. The documentation generally assumes downloading and building with `mvn install` so the artifact is made available in the local repository.
