### ISSUE TITLE
An error occurred while running mvn clean install

### ISSUE THREAD

**Issue by chensanf** [tada/pljava#210]
Hi, I'm having a problem running the "mvn clean install" command,Here is some of the output:

[1.txt](https://github.com/tada/pljava/files/2991275/1.txt)
```
[root@localhost pljava-1_5_2]# 
[root@localhost pljava-1_5_2]# mvn -v
Apache Maven 3.6.0 (97c98ec64a1fdfee7767ce5ffb20918da4f719f3; 2018-10-25T02:41:47+08:00)
Maven home: /opt/herodb/dbsrc/mvn/apache-maven-3.6.0
Java version: 1.8.0_60, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.60-1.8.nd7.02.mips64el/jre
Default locale: zh_CN, platform encoding: UTF-8
OS name: "linux", version: "3.10.0-2.nd7.17.mips64el", arch: "mips64el", family: "unix"
[root@localhost pljava-1_5_2]# 
[root@localhost pljava-1_5_2]# 
[root@localhost pljava-1_5_2]# java -version
openjdk version "1.8.0_60"
OpenJDK Runtime Environment (Loongson 8-loongson3a-NeoKylin) (build 1.8.0_60-8-b32)
OpenJDK 64-Bit Server VM (build 25.60-b24, mixed mode)
[root@localhost pljava-1_5_2]# 
[root@localhost pljava-1_5_2]# 
psql (11.2)
Type "help" for help.

postgres=# select version();
                                                    version                                                     
----------------------------------------------------------------------------------------------------------------
 PostgreSQL 11.2 on mips64el-unknown-linux-gnu, compiled by gcc (GCC) 4.9.3 20150626 (NeoKylin 4.9.3-3), 64-bit
(1 row)

postgres=# 

```

![111111111](https://user-images.githubusercontent.com/48084492/54740959-d390d380-4bf7-11e9-9b29-83777088fafb.PNG)

**Comment by jcflack** [comment]
Hello,

> 2. no linker is defined in the aol.properties file for 'mips64el.Linux.linker'

You might be the first person building PL/Java for `mips64el`. What kind of machine is it?

If you can, take a look in the `pljava-so` directory at the file `aol.ppc64le-linux-gpp.properties`. Make a copy of it named `aol.mips64el-linux-gpp.properties` and go through it to see if any of the definitions inside need to be changed for your architecture. (Of course, all the keys that start with `ppc64le.` need to be changed to start with `mips64el.`)

Then you can retry the build by adding `-Dnar.aolProperties=`_path/to/the/new/file_ on the `mvn` command line.

Once it works, if you submit the finished `aol.mips64el-linux-gpp.properties` here, I can add it to the distribution.

Thanks!

**Comment by chensanf** [comment]
Hello, I tried it the way you said:
1. Make a copy of aol.ppc64le-linux-gpp.properties called aol.mips64el-linux-gpp.properties
2. All keys starting with ppc64le in the file aol.mips64el-linux.gpp.properties are changed to mips64el
3. run the command: "mvn -Dnar.aolProperties=./pljava-so/aol.mips64el-linux-gpp.properties -X"
But now I've got some new mistakes:
[out.txt](https://github.com/tada/pljava/files/2994582/out.txt)
![789789](https://user-images.githubusercontent.com/48084492/54795228-3df05500-4c86-11e9-9665-7258242a63fd.PNG)

For line 34 of aol.mips64el-linux.gpp.properties, I tried three methods:
Ppc64le. Linux. GPP. Java. RuntimeDirectory = jre/lib/ppc64le/server
Mips64el. Linux. GPP. Java. RuntimeDirectory = jre/lib/ppc64le/server
Mips64el. Linux. GPP. Java. RuntimeDirectory = jre/lib/mips64el/server
This system is developed based on the Linux kernel

**Comment by chensanf** [comment]
Because of the upload problem, I changed the file to TXT format:
[aol.mips64el-linux-gpp.properties.txt](https://github.com/tada/pljava/files/2994602/aol.mips64el-linux-gpp.properties.txt)

**Comment by jcflack** [comment]
Hello,

That error is simply "no goals have been specified." When you run Maven, you should add the `-Dnar.aolProperties=./pljava-so/aol.mips64el-linux-gpp.properties` on the Maven command line, along with whatever other arguments would normally be there. So if the normal Maven command line would have some other option or profile settings and end with `clean install` (the two goals), the new command line should be just like that, except for also specifying the `nar.aolProperties` value.

If you look in the directory tree where your Java version is installed, you should be able to see what the correct name is for the `Java.RuntimeDirectory`.

**Comment by chensanf** [comment]
Oh my god, I was so careless, I thought I specified clean install。
But now it outputs：unrecognized command line option ‘-m64’
![741741](https://user-images.githubusercontent.com/48084492/54797037-9119d600-4c8d-11e9-8952-20c61c01a999.PNG)
I think that's the problem here：
![742742](https://user-images.githubusercontent.com/48084492/54797113-d3dbae00-4c8d-11e9-857a-ed8e14559c79.PNG)

**Comment by jcflack** [comment]
Right. You may have a little bit of research to do, finding out what command line options are correct for your mips64el version of gcc. Maybe it will help to look at the output of `pg_config` to see what compiler flags PostgreSQL itself used for the build.

**Comment by chensanf** [comment]
I received SUCCESS. 
1、When I run pg_config, I saw the following information:
![333333](https://user-images.githubusercontent.com/48084492/54798042-b0b2fd80-4c91-11e9-9b18-26f4e0a705e8.PNG)
2、Put the information for the variable CFLAGS into the previous copy，And then I saw：
![444444](https://user-images.githubusercontent.com/48084492/54798113-02f41e80-4c92-11e9-913d-3c3f3354c1d6.PNG)
3、Although this information is present during compilation, I don't think it is an error：
![666666](https://user-images.githubusercontent.com/48084492/54798147-2b7c1880-4c92-11e9-9a4e-d59374a28449.PNG)

Can I ask one more question, how can I use it now in my postgres (11.2)?
Thank you very much.good day!

**Comment by chensanf** [comment]
and This is the last file information I changed （Upload problem, I converted the format to TXT）：

[aol.mips64el-linux-gpp.properties.txt](https://github.com/tada/pljava/files/2994791/aol.mips64el-linux-gpp.properties.txt)

**Comment by chensanf** [comment]
Problem when "create extension":
![www](https://user-images.githubusercontent.com/48084492/54799341-b4498300-4c97-11e9-88f6-e3d59c428e63.PNG)
![eee](https://user-images.githubusercontent.com/48084492/54799343-b7dd0a00-4c97-11e9-9dac-3e4a39668fe4.PNG)

**Comment by jcflack** [comment]
If you have a `HINT: SET pljava.libjvm_location TO the correct path to the jvm library`, then you can look in the directory tree where your Java is installed to find the correct full path of `libjvm.so`, and give that to PostgreSQL, like so:

    SET pljava.libjvm_location TO '/usr/lib/jvm/whatever/whatever/something/libjvm.so';

You can tell when the value is right: PL/Java will work within that database session. Then you only need to save that setting so PL/Java will work in future sessions. You can use `ALTER DATABASE `_name-of-database_` SET pljava.libjvm_location FROM CURRENT;` to save the current setting that works.

More info: http://tada.github.io/pljava/install/install.html#PLJava_configuration_variables

If you like, you can choose the Java libjvm that you intend to use at the time you build PL/Java, and specify that path on the `mvn` command line when you build PL/Java. Then that will be the default path and `CREATE EXTENSION pljava` should just work with no need to set the variable first. You can still set the variable later if you want to have PL/Java run under a different Java implementation.

More info: http://tada.github.io/pljava/build/package.html

**Comment by chensanf** [comment]
thanks! Solved perfectly!

**Comment by chensanf** [comment]
Hi, I have one last question when I create the extension：
![rrr](https://user-images.githubusercontent.com/48084492/54803608-24adcf80-4cab-11e9-8a6e-9c1d58941f17.PNG)

What happened？

**Comment by jcflack** [comment]
I don't think I've seen that exactly before.

It might indicate that PL/Java was already installed, but not in the form of an extension. So you can say `CREATE EXTENSION pljava` and it tries to install again (because it does not see the extension installed), but trips over the parts of the installation that are already there.

That can happen if the first time you did `CREATE EXTENSION pljava` it didn't work, because the `pljava.libjvm_location` variable wasn't set. When you set the variable correctly, PL/Java finished installing, but it wasn't inside `CREATE EXTENSION` at that point.

If you do:

    \dn sqlj

does it show that an `sqlj` schema exists?

If so, that's probably what happened. You can finish the installation just by starting a new connection and doing the "from unpackaged" form of `CREATE EXTENSION`, like this:

    \c
    CREATE EXTENSION pljava FROM unpackaged;

That might be all you need.

**Comment by chensanf** [comment]
I have set pljava.libjvm_location before and I don't think pljava has been installed yet, now I run it again:
![ttt](https://user-images.githubusercontent.com/48084492/54804464-8de31200-4cae-11e9-9e00-660e84b54de5.PNG)

**Comment by chensanf** [comment]
> 之前我已经设置了pljava.libjvm_location，我认为还没有安装pljava，现在我再次运行它：
> ![TTT](https://user-images.githubusercontent.com/48084492/54804464-8de31200-4cae-11e9-9e00-660e84b54de5.PNG)

I haven't written anything to the database yet.This is an empty database and the first time pljava and postgresql are installed on this machine.

**Comment by chensanf** [comment]
I tried to solve it, but the result was inconsistent with the error information

```
postgres=# 
postgres=# DROP INDEX jar_repository_pkey;
ERROR:  index "jar_repository_pkey" does not exist
postgres=# 
postgres=# drop trigger if exists sys_trigger_jar_repository_pkey on jar_repository_pkey;
NOTICE:  relation "jar_repository_pkey" does not exist, skipping
DROP TRIGGER
postgres=# 

```

**Comment by jcflack** [comment]
If you do

    \sf public.sys_event_trigger_for_ddl

is there any sign where that function came from? It does not seem to be stock PostgreSQL 11.2.

**Comment by chensanf** [comment]
Here is the output：
![ttt](https://user-images.githubusercontent.com/48084492/54889034-3f678a80-4edd-11e9-9601-59123d1f90d6.PNG)

**Comment by jcflack** [comment]
You've said it's a fresh PostgreSQL installation and an empty database, but that event trigger function had to come from somewhere. My freshly built PG 11.2 does not have it.

It looks as if somebody was experimenting with writing an event trigger that would detect the use of a data type "mime" in tables, and automatically set up some triggers.

It also looks like it catches the relations PL/Java is trying to create, and tries to do trigger DDL on them, even when the relations are indexes and not tables.

I wonder if it is part of some extension you have installed. You could try:

    BEGIN READ WRITE;
    DROP FUNCTION public.sys_event_trigger_for_ddl();
    ROLLBACK;

By wrapping it in `BEGIN` and `ROLLBACK`, you will not really drop the function, but you might get some error message with a hint about where it came from.

**Comment by chensanf** [comment]
I see. I created an extension earlier, but one of the functions in the extension prevented me from creating pljava. Now I delete the previous extension and create pljava again without any error messages.You can then create the deleted extension without an error.Now I can use pljava. Thank you very much for your help.good day!

**Comment by jcflack** [comment]
Very good. Another option might have been to learn the name of the event trigger that was calling that function, say it was _foo_, and then try:

    ALTER EVENT TRIGGER foo DISABLE;
    CREATE EXTENSION pljava;
    ALTER EVENT TRIGGER foo ENABLE;

That might have worked. You might want to contact the maintainer of that other extension and explain that it tries to drop triggers on indexes.

I'll mark this issue closed.
