### ISSUE TITLE
environment variable

### ISSUE THREAD

**Issue by efynn** [tada/pljava#224]
Can 'SET pljava.libjvm_location TO' statement be replaced by setting the system environment variable?

**Comment by jcflack** [comment]
It can be set in any of the ways that apply to a restricted-to-superuser [PostgreSQL configuration variable][guc].

* You can manually edit the setting into the server's configuration file, and it will take effect the next time the server is started, or signaled to reload its configuration. It will apply to all databases in the cluster.
* You can use [ALTER SYSTEM SET ...][altsys], which edits the setting into `postgresql.auto.conf` for you. It will take effect in the same way, and apply to all databases in the cluster.
* You can set it with `-c` on the `postgres` or `pg_ctl` command line when starting the server, in which case it overrides anything in the configuration files until the server is stopped and restarted without it.
* You can use [ALTER DATABASE ... SET ...][altdb] which will establish the default setting for all connections to one particular database. It will take effect for all new connections to that database.
* You can use [ALTER ROLE ... SET ...][altrol] to establish a setting for all connections from a particular user to any database, or [ALTER ROLE ... IN DATABASE ... SET ...][altrol] to create a setting that applies whenever a particular user connects to a particular database.
* You can use `SET ...` during a session, if you are connected as a superuser, or you have done `SET ROLE` to a superuser role, but only before the first query in that session that causes PL/Java to successfully load; after that it's too late (without starting a new session).
* If you are connecting with `psql`, or with any software that uses `libpq`, you can put the setting in your [connection string][constr] as `options='-c pljava.libjvm_location=...'`, or in the [PGOPTIONS][] environment variable, and it will apply to the session that you open (but only if you are connecting as a user with superuser permission).

[guc]: https://www.postgresql.org/docs/current/config-setting.html
[altsys]: https://www.postgresql.org/docs/current/sql-altersystem.html
[altdb]: https://www.postgresql.org/docs/current/sql-alterdatabase.html
[altrol]: https://www.postgresql.org/docs/current/sql-alterrole.html
[constr]: https://www.postgresql.org/docs/12/libpq-connect.html#LIBPQ-CONNECT-OPTIONS
[PGOPTIONS]: https://www.postgresql.org/docs/current/libpq-envars.html

**Comment by efynn** [comment]
Thank you for your quick reply. It's very useful
