### ISSUE TITLE
pg_config.h file missing

### ISSUE THREAD

**Issue by brunre01** [tada/pljava#232]
pg_config:
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for PostgreSQL PL/Java 1.5.2:
[INFO]
[INFO] PostgreSQL PL/Java ................................. SUCCESS [  0.977 s]
[INFO] PL/Java API ........................................ SUCCESS [  1.331 s]
[INFO] PL/Java backend Java code .......................... SUCCESS [  1.327 s]
[INFO] PL/Java backend native code ........................ FAILURE [  3.509 s]
[INFO] PL/Java Deploy ..................................... SKIPPED
[INFO] PL/Java Ant tasks .................................. SKIPPED
[INFO] PL/Java examples ................................... SKIPPED
[INFO] PL/Java packaging .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.726 s
[INFO] Finished at: 2019-08-28T14:19:15-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.7:run (pg_config to pgsql.properties) on project pljava-so: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /home/postgres/software/pljava-1_5_2/pljava-so/build.xml:72: /usr/pgsql-11/include/pg_config.h doesn't exist
[ERROR] around Ant part ...<ant/>... @ 76:9 in /home/postgres/software/pljava-1_5_2/pljava-so/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pljava-so

What creates the pg_config.h  file?

**Comment by jcflack** [comment]
If your PostgreSQL installation is from a package repository, is there also a `-devel` package to go with it? Typically, that is where the `.h` files will be.

**Comment by jcflack** [comment]
Closing, believed not to indicate a PL/Java bug.
