### ISSUE TITLE
Could not load library: Error relocating. AllocSetContextCreateInternal: symbol not found

### ISSUE THREAD

**Issue by tomansill** [tada/pljava#252]
I am trying to install pljava 1.5.5 in existing [Timescaledb's Postgis docker image](https://hub.docker.com/r/timescale/timescaledb-postgis/) and I have encountered an error that prevents me from loading pljava into my Postgresql instance.

The error says:

```
postgres=# CREATE EXTENSION pljava;
ERROR:  could not load library "/usr/local/lib/postgresql/libpljava-so-1.5.5.so": Error relocating /usr/local/lib/postgresql/libpljava-so-1.5.5.so: AllocSetContextCreateInternal: symbol not found
```

Steps that I have done leading to this issue:

1. Set Git commit to 1.5.5 release (commit c0ada5946bc00b021c6fb3356348ae66f4b85591)
2. `mvn clean install` to produce jar. 
3. Copy the jar into a running Timescaledb Postgis docker container
4. Install java runtime in container
5. Run `java -jar` from inside of container to install pljava
6. Log into Postgresql 
7. `SET pljava.libjvm_location TO '/usr/lib/jvm';`
8. `CREATE EXTENSION pljava;`

I have verified that pljava files exists in Postgres' installation area:

```sh
bash-5.0# ls -Al /usr/local/lib/postgresql/libpljava-so-1.5.5.so 
-rwxr-xr-x    1 root     root        333808 Feb  6 01:03 /usr/local/lib/postgresql/libpljava-so-1.5.5.so

bash-5.0# ls -Al /usr/local/share/postgresql/pljava/
total 696
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.0--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.0-BETA1--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.0-BETA2--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.0-BETA3--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.1--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.1-BETA1--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.1-BETA2--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.1-BETA3--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.2--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.3--1.5.5.sql
-rwsr--r--    1 root     root          2433 Feb  6 01:03 pljava--1.5.4--1.5.5.sql
-rwsr--r--    1 root     root          3228 Feb  6 01:03 pljava--1.5.5.sql
-rwsr--r--    1 root     root          3580 Feb  6 01:03 pljava--unpackaged--1.5.5.sql
-rwsr--r--    1 root     root        451839 Feb  6 01:03 pljava-1.5.5.jar
-rwsr--r--    1 root     root         91655 Feb  6 01:03 pljava-api-1.5.5.jar
-rwsr--r--    1 root     root        109440 Feb  6 01:03 pljava-examples-1.5.5.jar
```

I have searched for similar issues on internet but they have not helped me so far. I am suspecting that it's probably because that pljava is compiled for Postgres 12 and this server instance is running on Postgres 11. I have looked through the pljava build files and I don't see a such configuration option to target Postgres 11. I'm out of options here. 

Could anyone please help me with this issue?

Thank you

**Comment by tomansill** [comment]
As I have reviewed the documentation, I learned that you need to target an existing `pg_config` to instruct Maven to use specific Postgresql configuration. After targeting it to correct version. I'm able to get it to load.

**Comment by jcflack** [comment]
Glad you found it!
