### ISSUE TITLE
64bit Ubuntu/Debian package

### ISSUE THREAD

**Issue by petebrew** [tada/pljava#27]
I see that there is a problem with the 64bit build of pljava: 
https://bugs.launchpad.net/ubuntu/+source/postgresql-pljava/+bug/1301150

Is anyone willing and able to look into this?  It's way above my pay grade but I've come to rely upon pljava and no 64bit is a serious issue for me.

**Comment by jcflack** [comment]
OIC.  The version that Ubuntu is (still) building, and Debian gave up on, is from 2011, pre-Maven-move, _and_ built with GCJ:

http://bazaar.launchpad.net/~ubuntu-branches/ubuntu/wily/postgresql-pljava/wily/files/head:/debian/

I suppose they can't be blamed, as that was the last anything called a 'release' happened here. But it would be great if they were using the newer stuff, and building against openjdk.

I guess the process ought to start by turning 0.0.2-SNAPSHOT to 1.5.0-SNAPSHOT in the pom version tag....

Until then, for anyone who needs the package and has trouble with the Ubuntu one, the snapshot is downloadable and buildable with Maven.

**Comment by jcflack** [comment]
Have sent e-mail to alert the maintainer of the debian/ubuntu package that a 1.5.0 is in the works.

**Comment by ChristophBerg** [comment]
There are working packages now on apt.postgresql.org. Covered:
* Debian unstable/buster/stretch
* Ubuntu cosmic/bionic/xenial
* amd64/i386/ppc64el

Package info for https://github.com/tada/pljava/wiki/Prebuilt-packages:

`{1.5.2,"11.1 (Debian 11.1-1.pgdg+1)",11.0.1,Linux,amd64}`

(There are chances to have pljava properly included in Debian (and in turn in Ubuntu), but that will likely need some build-deps to be packaged first; I haven't investigated yet.)

**Comment by jcflack** [comment]
I think I left this issue open two years ago to remind myself to update the wiki page about it, which I have now done. Closing.

**Comment by df7cb** [comment]
The info is unfortunately already outdated, it's of course up to PG 13, the architecture includes arm64 now, and the most recent Ubuntu LTS release is focal.
To have this not a fully moving target, I'd just write "pljava is fully supported on all distributions, architectures, and PostgreSQL versions that are supported on apt.postgresql.org" or something like that.
