### ISSUE TITLE
Support of arrays in composite types

### ISSUE THREAD

**Issue by yazun** [tada/pljava#300]
I was wondering if anything progressed since this issue has been reported?
https://www.postgresql-archive.org/Arrays-support-for-object-views-td2207372.html

i.e. would updateObject work now to return an array of say Double[] or double[].

Is my understanding correct that returning multidimensional array would not work at all, i.e. Double[][] or double[][] would never be coerced to float8[][]? Documentation is bit vague on this subject.

Thank you,
Krzysztof

**Comment by jcflack** [comment]
I've added the current state of play [to that original email thread][eml].

I had not been looking very closely at the array support. In assessing where it currently stands, I found a couple of small bugs that I'll look into fixing in the current released (1.5.x) and upcoming (1.6) branches. I think multidimensionality will be more than I want to get into until after 1.6.

[eml]: https://www.postgresql.org/message-id/5F63FD3C.3080206%40anastigmatix.net

**Comment by yazun** [comment]
Big thanks for the elaborated and fast answer. 

I can confirm that now something like this:
```java
receiver.updateObject(1,new Double[][] {{1.0,2.0},{1.1,2.1}});
```
will result in 
`message:java.sql.SQLException: Cannot derive a value of class [Ljava.lang.Float; from an object of class [[Ljava.lang.Float;`

We will try to find a workaround for now, probably making a projection as an array of composite objects with embedded 1D arrays. 
I hope this should work.

**Comment by jcflack** [comment]
What version are you running?

If you're willing to build from an unreleased branch, I could push one that would have a superuser-settable developer option enabling you to get a raw [`VarlenaWrapper.Output`][vwo] as an `OutputStream` for a PostgreSQL array type, and write into it from Java. You'd have to look over the [internal format for a PostgreSQL array][arr] and write it out correctly (starting with _ndim_; the *_vl_len* is handled for you by the `VarlenaWrapper`). The format is not too crazy: how many dimensions, what are they, what are the base indices, null bitmap if allowing nulls, and the values.

It would have to be a developer option because by not getting the format right you'd be giving PostgreSQL bogus data.

You would only be able to handle by-value element types like the Java primitives, but it sounds like that might be all you need. If you were then willing to contribute the code under the project license, it could become the skeleton for built-in support in a later version.

[vwo]: https://tada.github.io/pljava/pljava/apidocs/org/postgresql/pljava/internal/VarlenaWrapper.Output.html
[arr]: https://git.postgresql.org/gitweb/?p=postgresql.git;a=blob;f=src/include/utils/array.h;hb=HEAD

**Comment by yazun** [comment]
Looks like we skipped few versions: Still on 1.5.1-BETA. 

This sounds tempting! Yes, we are after primitive multidimensional arrays at this point. 
Could you point me to the marshalling/layout code that deals with arrays - so we could write a marshaller?

Of course we are happy to contribute the code if anything useful emerges.
Thanks!

**Comment by yazun** [comment]
As a side note: we are still on Java 8 (and PG10 fork, Centos 8) and it will take another few months until we are to a newer JDK - I noticed/remembered master does not compile on JDK 8 anymore as requires --release flag?

I could not spot any mention how to re-enable Java 8 in the documentation, I could create another issue if you think it makes sense.

Also in the past we had to tweak output of PG version from pg_config as it was straying from standard PG relase/version pattern name.
```
DEBUG] -d /home/pgxzDR3/git/pljava_master.git/pljava-api/target/classes -classpath /home/pgxzDR3/git/pljava_master.git/pljava-api/target/classes: -sourcepath /home/pgxzDR3/git/pljava_master.git/pljava-api/src/main/java:/home/pgxzDR3/git/pljava_master.git/pljava-api/target/generated-sources/annotations: -s /home/pgxzDR3/git/pljava_master.git/pljava-api/target/generated-sources/annotations -g --release 9 -encoding UTF-8 --module-version 1.6.0-SNAPSHOT
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 27 source files to /home/pgxzDR3/git/pljava_master.git/pljava-api/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] PostgreSQL PL/Java ................................ SUCCESS [1.044s]
[INFO] PL/Java API ....................................... FAILURE [0.371s]
[INFO] PL/Java backend Java code ......................... SKIPPED
[INFO] PL/Java PGXS ...................................... SKIPPED
[INFO] PL/Java backend native code ....................... SKIPPED
[INFO] PL/Java Ant tasks ................................. SKIPPED
[INFO] PL/Java examples .................................. SKIPPED
[INFO] PL/Java packaging ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.605s
[INFO] Finished at: Mon Sep 21 11:33:28 CEST 2020
[INFO] Final Memory: 30M/1963M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pljava-api: Fatal error compiling: invalid flag: --release -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project pljava-api: Fatal error compiling
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:217)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1145)
        at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
        ... 19 more
Caused by: org.codehaus.plexus.compiler.CompilerException: invalid flag: --release
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:173)
        at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
        at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: invalid flag: --release
        at com.sun.tools.javac.api.JavacTool.processOptions(JavacTool.java:206)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:156)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:107)
        at com.sun.tools.javac.api.JavacTool.getTask(JavacTool.java:64)
        at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:125)
        ... 24 more
```

**Comment by jcflack** [comment]
The master branch/1.6.x upcoming release will be 100% committed to Java 9 and later; many Java 9 features are used in the code.

Therefore, if I make a branch with a raw-memory option where you can write an array marshaller, I'll have to make that a branch from `REL1_5_STABLE`. There will be at least one more 1.5.x release; it is not going away immediately.

Of course I invite you to consider migrating to Java 9 or later as soon as convenient. There's a lot to like.

Fortunately, the `VarlenaWrapper` class that would allow you to do the work does exist in `REL1_5_STABLE`; it was introduced as infrastructure with the XML support. PL/Java's existing marshallers (pre-XML, pre-`VarlenaWrapper`) are split awkwardly between Java and C in a way you won't want to emulate ... and XML is a different-enough kind of beast that its marshaller, though it uses `VarlenaWrapper`, won't tell you much useful for arrays.

My earlier comment did link to PostgreSQL's `array.h` where the format is described.

Does the email address you used on the pljava-dev thread still work? If you're game to work on an array marshaller, perhaps we should jump back over there to talk shop.

**Comment by jcflack** [comment]
On the Java versions, I should add that while PL/Java 1.6.x will require Java 9+ to build and run, any existing user code you have written for earlier Java versions will still work; you don't need to do anything Java 9-specific to make it work in the later PL/Java.

Likewise, you can write user code that uses later Java features and run it even with PL/Java 1.5.x, provided `pljava.libjvm_location` is pointing to a JVM version that can run the code you've written.

1.5.x will definitely stop building successfully with Java 15 though, where the built-in JavaScript support used in the build procedure goes away.

**Comment by yazun** [comment]
We can move to Jdk11 for PL/Java only indeed and switch to PL/Java 1.6 then.
It's always bit cumbersome to have two multiple environments but it should not hurt indeed. We would like to move to Graal eventually but not in coming months. Right now we are too busy with data crunching to do so for our HPC pipeline.

Thanks for the pointers, I missed the hyperlink to the array.h on the first read, sorry.

**Comment by yazun** [comment]
And yes, the email used in pljava-dev still works!

**Comment by jcflack** [comment]
Is it ok then if I continue the discussion on building an array marshaller over there in that pljava-dev thread?

**Comment by jcflack** [comment]
I've made a pull request (#307) that will go first into `REL1_5_STABLE` and soon into `master` (-> 1.6), resolving the issues that were identified here except for multidimensionality. PL/Java code an request a PostgreSQL array in either Java primitive-array or boxed-array form (by passing the corresponding class argument to the `ResultSet.getObject` that takes a class), and can pass either the boxed or the primitive array form into `updateObject`, nulls are handled (when the boxed form is used), and the conversion from `Byte[]` doesn't mess up the values.

Krzysztof, are you still interested in working on a marshaller that can handle multiple dimensions?

**Comment by yazun** [comment]
Thanks a lot for this one.
Yes, definitely. Time is sparse though. Will try to find some in coming weeks.

**Comment by jcflack** [comment]
1.5.6 is released now, and will let you use boxed or primitive Java arrays with `getObject` and `updateObject`, and the boxed ones can have null values. Still just one dimension though. This support will also be in the upcoming 1.6.0.

I will close this issue but suggest we continue talking about a better array marshaller over in [the pljava-dev thread][dev]. I'll head over there now and add some initial thoughts.

[dev]: https://www.postgresql.org/message-id/5F63FD3C.3080206%40anastigmatix.net
