### ISSUE TITLE
Build error against PostgreSQL 13

### ISSUE THREAD

**Issue by devrimgunduz** [tada/pljava#302]
Hi,

1.5.5 fails to build against PostgreSQL 13. 13.0 is out today. When will you release a new version compatible with v13?

Regards, Devrim

**Comment by jcflack** [comment]
Soon, maybe this weekend. Changes to build against 13beta1 have been in the tree a while; I need to recheck nothing more broke since beta1, write release notes, etc.

**Comment by devrimgunduz-edb** [comment]
Hi,

Any updates?

Regards, Devrim

**Comment by devrimgunduz** [comment]
Hi @jcflack ,

Any updates?

Regards, Devrim

**Comment by df7cb** [comment]
1.5.6 worked for me on PG13, fwiw.

**Comment by jcflack** [comment]
Believed resolved in 1.5.6.
