### ISSUE TITLE
I can't install pl/java on CentOS

### ISSUE THREAD

**Issue by DacKiller** [tada/pljava#31]
I try to many times, but its not working..

CentOS / 64bits
Java JRE 1.6
Response from PostgreSQL 9.3:

could not load library "/usr/pgsql-9.3/lib/pljava.so": /usr/pgsql-9.3/lib/pljava.so: undefined symbol: disable_sig_alarm

Env Vairables:

$JRE_HOME=/usr/java/jre
$LD_LIBRARY_PATH=$JRE_HOME/lib/amd64:$JRE_HOME/lib/amd64/server

PostgreSQL.conf
pljava.classpath='/usr/pgsql-9.3/share/pljava/pljava.jar'

Do you know that problem on PostgreSQL 9.3 ?

**Comment by jcflack** [comment]
This issue was closed with pull request #19.
