### ISSUE TITLE
mvn package : Cannot deduce version number from:

### ISSUE THREAD

**Issue by amoshiyan** [tada/pljava#32]
Hello! 
I downloaded project from https://github.com/tada/pljava .  
Then try to package them. And get error on pljava-so module:

: [ERROR] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Cannot deduce version number from:

Apache Maven 2.2.1 
Java version: 1.6.0_45

How to resolve this problem? Thanks in advance.

**Comment by jcflack** [comment]
Probably too late for the OP, but for the benefit of anyone else who wonders about that message:

It comes from the [nar-maven-plugin][nar] (which does the compiling/linking of the .so) when the plugin has looked for the command-line tools used for compiling (g++, msvc, link, whatever) and not found them, or found something that didn't give a recognizable string when run with the appropriate "version" option. Typically this would mean the right development tools package wasn't installed, or the path was not configured to find it.

Not a PL/Java issue - closing.

[nar]: https://github.com/maven-nar/nar-maven-plugin/blob/5889a13d495beaca6ad1362672d45f2ba477c261/src/main/java/org/apache/maven/plugin/nar/Linker.java#L249
