### ISSUE TITLE
JDK 1.7, PostgreSQL 9.3.5, nar-maven-plugin 3.1.0 

### ISSUE THREAD

**Issue by fbroda** [tada/pljava#33]
I managed to build pljava [[https://github.com/fbroda/pljava/tree/jdk7]] under openSUSE 13.1 (x86_64) for JDK 1.7 (Oracle JavaSE 1.7.0.71) and PostgreSQL 9.3.5 using forks from @sptrakesh and @gdmSISouth. Especially the nar-maven-plugin gave me a hard time (release 3.1.0 works, 3.2.0 doesn't work for me). I made a mess, because I didn't read the guidelines for contributors early and carefully (therefore I started in branch master and continued in ill-named branch jdk7). 

There are still some issues with pljava-examples but I currently can't tell exactly what needs to be fixed there. The simpler stuff seems to work though.

Anyway, I would like to see support for JDK 1.7 in PL/Java. If I need to fix / polish / whatever my branch, before it's ready for integration into the master repository, I could possibly spend a few hours.

**Comment by jcflack** [comment]
This issue appears closed by the merge of #35.
