### ISSUE TITLE
Docker image for PL/Java 1.6.2 on Postgres 11.11

### ISSUE THREAD

**Issue by adrianescutia** [tada/pljava#339]
I have built an image for PL/Java 1.6.2 on Postgres 11.11

`{1.6.2,"11.11 (Debian 11.11-1.pgdg90+1)",11.0.6,Linux,amd64}`

`docker pull adrianescutia/postgres11-pljava:1.6.2`

Guide to configure [here](https://adrianescutia.github.io/adrianes/docs/postgres/enable-pljava-in-a-postgres-database).

CC: @jcflack

**Comment by jcflack** [comment]
Thanks! Added to the wiki.
