### ISSUE TITLE
Add support PostgreSQL 9.4

### ISSUE THREAD

**Issue by pmichalek** [tada/pljava#37]
Please add support for PostgreSQL 9.4. Thanks!

**Comment by shawjef3** [comment]
I was hoping I could fix pljava for 9.4, but I don't know how to turn off -Wall. There are so many warnings during compile that I can't find what is causing the build to fail.

**Comment by shawjef3** [comment]
After looking at the output directory and comparing its contents against the input directories, I discovered that the only file failing to compile was Oid.c. I fixed the problem and now I am able to compile pljava against PostgreSQL 9.4. I can't guarantee that it works correctly, though.

https://github.com/tada/pljava/pull/38

**Comment by raja1408** [comment]
Hi, 
I am new to postgres, can you please help me  to compile pljava. I have postgres on a centos. Thanks in advance.

**Comment by jcflack** [comment]
This issue appears closed by the merge of #38.
