### ISSUE TITLE
PL/Java backend failing - can't link with a main executable file '/usr/local/Cellar/postgresql/14.0/bin/postgres'

### ISSUE THREAD

**Issue by reenarsingh** [tada/pljava#377]
Hi, I am new to building PL/Java. The build is failing with below error on apple M1
can't link with a main executable file '/usr/local/Cellar/postgresql/14.0/bin/postgres' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Java version is 17.0.1
Postgres is 14. 
If I try to execute "/usr/local/Cellar/postgresql/14.0/bin/postgres" directly it works. 
Environment variables set - 
MPDIR=/var/folders/wh/4zkvwl357316g_hc7xl6qrbh0000gn/T/
__CFBundleIdentifier=com.apple.Terminal
XPC_FLAGS=0x0
TERM=xterm-256color
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.tapRStkP6d/Listeners
XPC_SERVICE_NAME=0
TERM_PROGRAM=Apple_Terminal
TERM_PROGRAM_VERSION=440
TERM_SESSION_ID=DB5AC787-FBDB-44D5-A5F5-D3077F04C4DA
SHELL=/bin/zsh
HOME=/Users/reenasingh
LOGNAME=reenasingh
USER=reenasingh
PATH=/Users/reenasingh/opt/anaconda3/bin:/Users/reenasingh/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/VMware Fusion Tech Preview.app/Contents/Public:/Users/reenasingh/programfiles/apache-maven-3.8.3/bin:/Users/reenasingh/programfiles/apache-maven-3.8.3/bin:/Users/reenasingh/programfiles/apache-maven-3.8.3/bin
SHLVL=1
PWD=/Users/reenasingh/programfiles/pljava-1_6_3
OLDPWD=/Users/reenasingh
CONDA_EXE=/Users/reenasingh/opt/anaconda3/bin/conda
_CE_M=
_CE_CONDA=
CONDA_PYTHON_EXE=/Users/reenasingh/opt/anaconda3/bin/python
CONDA_SHLVL=1
CONDA_PREFIX=/Users/reenasingh/opt/anaconda3
CONDA_DEFAULT_ENV=base
CONDA_PROMPT_MODIFIER=(base) 
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk-17.0.1.jdk/Contents/Home
M2_HOME=/Users/reenasingh/programfiles/apache-maven-3.8.3
PGDATA=/usr/local/var/postgres
LANG=en_CA.UTF-8

PG_config results -
BINDIR = /usr/local/Cellar/postgresql/14.0/bin
DOCDIR = /usr/local/Cellar/postgresql/14.0/share/doc/postgresql
HTMLDIR = /usr/local/Cellar/postgresql/14.0/share/doc/postgresql
INCLUDEDIR = /usr/local/include
PKGINCLUDEDIR = /usr/local/include/postgresql
INCLUDEDIR-SERVER = /usr/local/include/postgresql/server
LIBDIR = /usr/local/lib
PKGLIBDIR = /usr/local/lib/postgresql
LOCALEDIR = /usr/local/Cellar/postgresql/14.0/share/locale
MANDIR = /usr/local/Cellar/postgresql/14.0/share/man
SHAREDIR = /usr/local/share/postgresql
SYSCONFDIR = /usr/local/etc/postgresql
PGXS = /usr/local/lib/postgresql/pgxs/src/makefiles/pgxs.mk
CONFIGURE =  '--disable-debug' '--prefix=/usr/local/Cellar/postgresql/14.0' '--datadir=/usr/local/share/postgresql' '--libdir=/usr/local/lib' '--includedir=/usr/local/include' '--sysconfdir=/usr/local/etc' '--docdir=/usr/local/Cellar/postgresql/14.0/share/doc/postgresql' '--enable-thread-safety' '--with-gssapi' '--with-icu' '--with-ldap' '--with-libxml' '--with-libxslt' '--with-openssl' '--with-pam' '--with-perl' '--with-uuid=e2fs' '--with-bonjour' '--with-tcl' 'PG_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk' 'CC=clang' 'LDFLAGS=-L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib' 'CPPFLAGS=-I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include' 'CXX=clang++' 'PKG_CONFIG_PATH=/usr/local/opt/icu4c/lib/pkgconfig:/usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/krb5/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig' 'PKG_CONFIG_LIBDIR=/usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/11'
CC = clang
CPPFLAGS = -I/usr/local/Cellar/icu4c/69.1/include -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/readline/include
CFLAGS = -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Werror=unguarded-availability-new -Wendif-labels -Wmissing-format-attribute -Wformat-security -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2
CFLAGS_SL = 
LDFLAGS = -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk -L/usr/local/opt/openssl@1.1/lib -L/usr/local/opt/readline/lib -Wl,-dead_strip_dylibs
LDFLAGS_EX = 
LDFLAGS_SL = 
LIBS = -lpgcommon -lpgport -lxslt -lxml2 -lpam -lssl -lcrypto -lgssapi_krb5 -lz -lreadline -lm 
VERSION = PostgreSQL 14.0

Printed all the variables set for MACOSX by using print command in POM
Using compiling/linking rules for Mac OS X
Reena["clang","-isysroot","/Library/Developer/CommandLineTools/SDKs/MacOSX11.sdk","-L/usr/local/opt/openssl@1.1/lib","-L/usr/local/opt/readline/lib","-Wl,-dead_strip_dylibs","-bundle_loader","/usr/local/Cellar/postgresql/14.0/bin/postgres","-bundle","-o","libpljava-so-1.6.3.bundle","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Type.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Time.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Invocation.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Oid.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Composite.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/BigDecimal.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/ErrorData.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Relation.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/PgSavepoint.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/TypeOid.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Portal.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Float.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Short.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SQLXMLImpl.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Void.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Backend.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/TupleTable.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Date.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SingleRowReader.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/TriggerData.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/HashMap.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Long.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/XactListener.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SQLOutputToChunk.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SQLInputFromChunk.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/PgObject.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Boolean.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SubXactListener.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/ExecutionPlan.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Session.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Coerce.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/AclId.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/byte_array.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/TupleDesc.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Array.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Double.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SPI.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Tuple.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/VarlenaWrapper.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/DualState.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Exception.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Integer.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Iterator.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Timestamp.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/UDT.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Byte.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Function.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/Any.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SQLOutputToTuple.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/InstallHelper.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/SQLInputFromTuple.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/JNICalls.o","/Users/reenasingh/programfiles/pljava-1_6_3/pljava-so/target/pljava-pgxs/String.o"]

**Comment by reenarsingh** [comment]
It worked, after I downgraded my java version from 17 to 11.

**Comment by jcflack** [comment]
Hi, thanks for the report.

I have not seen this before, and I wonder if there is some complication with using the `-bundle_loader` linker argument on M1. A quick Google search shows that there [may be some related reports][n1] in other (non-PL/Java) projects.

Our comments crossed; it is now extra interesting that you see the issue with JDK 17 and not with JDK 11.

I assume the error message you are reporting came during the `pljava-so` project build from Maven? So, before any attempt to test the build result?

I wonder if there is any option that can be added for `ld` to show exactly what (some symbol clash?) went wrong when it attempted the link.

[n1]: https://www.google.com/search?hl=en&gbv=1&q=%22can%27t+link+with+a+main+executable%22+%22for+architecture+arm64%22&oq=&aqs=
