### ISSUE TITLE
Execute multiple SQL statements in a java method, is it in a transaction?

### ISSUE THREAD

**Issue by dengpan1** [tada/pljava#382]
I executed multiple SQL statements, but threw exceptions, they all rolled back, I do not want them in one transaction, what should I do ?

**Comment by jcflack** [comment]
PostgreSQL 11 [added][udp] "user-defined procedures", which are used with `CALL` in SQL, and can start and commit their own transactions, but PL/Java does not support those yet. In PL/Java you can only create functions, and a function always executes inside the transaction of the query that calls it.

However, you can use the JDBC `Connection` methods [`setSavepoint`][ssp], [`releaseSavepoint`][rsp] (which is like committing the savepoint), and [`rollback`][rb].

If your code catches an exception, it must rollback to a prior savepoint before it can further interact with the database.

An example can be seen [inside PL/Java itself][ex], where it creates the `sqlj` schema but recovers if the schema already exists (error code 42P06). If the exception has any other error code, it is simply rethrown.

[udp]: https://www.postgresql.org/docs/11/release-11.html#id-1.11.6.19.5.8
[ssp]: https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#setSavepoint--
[rsp]: https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#releaseSavepoint-java.sql.Savepoint-
[rb]: https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#rollback-java.sql.Savepoint-
[ex]: https://github.com/tada/pljava/blob/V1_6_3/pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java#L435

**Comment by dengpan1** [comment]
> PostgreSQL 11 [added](https://www.postgresql.org/docs/11/release-11.html#id-1.11.6.19.5.8) "user-defined procedures", which are used with `CALL` in SQL, and can start and commit their own transactions, but PL/Java does not support those yet. In PL/Java you can only create functions, and a function always executes inside the transaction of the query that calls it.
> 
> However, you can use the JDBC `Connection` methods [`setSavepoint`](https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#setSavepoint--), [`releaseSavepoint`](https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#releaseSavepoint-java.sql.Savepoint-) (which is like committing the savepoint), and [`rollback`](https://docs.oracle.com/javase/9/docs/api/java/sql/Connection.html#rollback-java.sql.Savepoint-).
> 
> If your code catches an exception, it must rollback to a prior savepoint before it can further interact with the database.
> 
> An example can be seen [inside PL/Java itself](https://github.com/tada/pljava/blob/V1_6_3/pljava/src/main/java/org/postgresql/pljava/internal/InstallHelper.java#L435), where it creates the `sqlj` schema but recovers if the schema already exists (error code 42P06). If the exception has any other error code, it is simply rethrown.

ok, so how do I set autoCommit to true? [SPIConnection.getAutoCommit](https://github.com/tada/pljava/blob/master/pljava/src/main/java/org/postgresql/pljava/jdbc/SPIConnection.java#L218) method always return false, can I change the source code here to true and recompile ?

**Comment by jcflack** [comment]
You can't; it wouldn't work. The transaction of the query that calls your Java function begins before the function call and cannot be committed until after your function returns.
