### ISSUE TITLE
"Error loading shared library libjvm.so"—printed by Java, loaded from there! Alpine linux, Docker

### ISSUE THREAD

**Issue by udesaiitrs** [tada/pljava#383]
Hello, I have been trying to setup a basic installation of Postgres with the PL/Java extension and cannot get past the installation step. I am creating and running a docker image with a Dockerfile of:

```
FROM timescale/timescaledb:2.3.1-pg12

ARG MAVEN_VERSION=3.8.4
ARG USER_HOME_DIR="/root"
ARG BASE_URL=https://apache.osuosl.org/maven/maven-3/${MAVEN_VERSION}/binaries
ARG PLJAVA_VERSION=1_6_3

RUN apk --no-cache add curl tar openssl-dev build-base openjdk11 && \
    mkdir -p /usr/share/maven /usr/share/maven/ref && \
    curl -fsSL -o /tmp/apache-maven.tar.gz ${BASE_URL}/apache-maven-${MAVEN_VERSION}-bin.tar.gz && \
    tar -xzf /tmp/apache-maven.tar.gz -C /usr/share/maven --strip-components=1 && \
    rm -f /tmp/apache-maven.tar.gz && \
    ln -s /usr/share/maven/bin/mvn /usr/bin/mvn && \
    curl -fsSL -o /tmp/pljava_${PLJAVA_VERSION}.tar.gz  https://github.com/tada/pljava/archive/refs/tags/V${PLJAVA_VERSION}.tar.gz && \
    tar -xzf /tmp/pljava_1_6_3.tar.gz -C /tmp && \
    cd /tmp/pljava-1_6_3/ && \
    mvn clean install && \
    java -jar pljava-packaging/target/pljava-pg12.jar

ENV MAVEN_HOME /usr/share/maven
ENV MAVEN_CONFIG "$USER_HOME_DIR/.m2"
```

I also have tried adding the following entries to my postgresql.conf file: 
```
pljava.module_path = '/usr/local/share/postgresql/pljava/pljava-1.6.3.jar:/usr/local/share/postgresql/pljava/pljava-api-1.6.3.jar'
pljava.libjvm_location = '/usr/lib/jvm/java-11-openjdk/lib/server/libjvm.so' 
```

When I run "CREATE EXTENSION pljava" I get the following error in the postgres log:

```
Error occurred during initialization of VM

Unable to load native library: Error loading shared library libjvm.so: No such file or directory (needed by /usr/lib/jvm/java-11-openjdk/lib/libjava.so)


2021-12-16 20:28:32.641 UTC [40] FATAL: the Java VM exited while loading PL/Java

2021-12-16 20:28:32.641 UTC [40] DETAIL: The Java VM's exit forces this session to end.

2021-12-16 20:28:32.641 UTC [40] HINT: This has been known to happen when the entry in pljava.module_path for the pljava-api jar has been misspelled or the jar cannot be opened. If logging_collector is active, there may be useful information in the log.
```

The base image used is a Timescale (postgres extension) image and it is running PG 12. 

Any help is appreciated and thanks in advance!

**Comment by udesaiitrs** [comment]
Furthermore, I have indeed verified that the location of the libjvm.so file is correct.

**Comment by jcflack** [comment]
That's quite peculiar, nothing I have seen happen before.

The `libjvm.so` is clearly being successfully found and loaded, because the Java VM is clearly started up and initializing. It gets as far as looking for one of its additional libraries (`libjava.so`), and then complains from loading *that* library that it can't find `libjvm.so`—*which is the library it already was loaded from*!

Can you supply any more details about the operating system and the version and provider of Java involved?

You might get some useful information with `SET log_min_messages TO debug2` in PostgreSQL before loading PL/Java.

The problem should not have anything to do with the setting of `pljava.module_path`; that should have the correct default in most cases, so I would recommend *not* having that line in `postgresql.conf`; it could just lead to confusion at some later date.

**Comment by jcflack** [comment]
In a search like

> "Error loading shared library" libjvm.so "No such file or directory" "needed by" libjava.so

some hits come up, involving other software, not PL/Java. In some of the reports, there seems to be something specific to a particular build of Java on a particular build of Linux. Some of the reports include a note that it was made to work with an explicit setting of `LD_LIBRARY_PATH`.

Mucking with `LD_LIBRARY_PATH` would seem kludgy to me, and even if it resolved the issue, I still would be somewhat unsatisfied until finding out *why* it was needed. It is very unusual for Java to say it can't find the library it just got loaded from.

**Comment by udesaiitrs** [comment]
The base image is Alpine Linux 3.14, and the java version I originally tried was: 
```
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment (build 11.0.12+7-alpine-r0)
OpenJDK 64-Bit Server VM (build 11.0.12+7-alpine-r0, mixed mode)
```

I tried with java 10 and it gave the same exact error. Enabling the debug logging also didn't show anything new/helpful.
```
openjdk version "10.0.2" 2018-07-17
OpenJDK Runtime Environment (build 10.0.2+13-alpine-r3)
OpenJDK 64-Bit Server VM (build 10.0.2+13-alpine-r3, mixed mode)
```

I tried setting `LD_LIBRARY_PATH` as well, but no luck the error is the same. In addition, I tried setting the other Java env vars that might be needed to:
```
export JAVA_HOME='/usr/lib/jvm/default-jvm/'
export LD_LIBRARY_PATH='/usr/lib/jvm/default-jvm/lib/server/:/usr/lib/:/lib/'
export PATH='/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/lib/jvm/default-jvm/bin'
```

I suppose if you tried with the same dockerfile locally it would result in the same issue?

**Comment by udesaiitrs** [comment]
I also verified all the paths for the files are correct. The output of the pljava installation command is as follows:
```
# java -jar pljava-packaging/target/pljava-pg12.jar
/usr/local/lib/postgresql/libpljava-so-1.6.3.so as bytes
/usr/local/share/postgresql/pljava/pljava-1.6.3.jar as bytes
/usr/local/share/postgresql/pljava/pljava-api-1.6.3.jar as bytes
/usr/local/share/postgresql/pljava/pljava-examples-1.6.3.jar as bytes
/usr/local/share/postgresql/extension/pljava.control as lines (ASCII)
/usr/local/share/postgresql/pljava/pljava--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--unpackaged--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.6.2--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.6.1--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.6.0--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.8--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.7--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.6--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.5--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.4--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.3--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.2--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.1--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.1-BETA3--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.1-BETA2--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.1-BETA1--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.0--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.0-BETA3--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.0-BETA2--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--1.5.0-BETA1--1.6.3.sql as lines (UTF8)
/usr/local/share/postgresql/pljava/pljava--unpackaged.sql as lines (UTF8)
/usr/local/etc/postgresql/pljava.policy as lines (UTF8)
```

**Comment by udesaiitrs** [comment]
Wow, so I tried to add a symlink of the `libjvm.so` file into the directory where `libjava.so` lives, and then the extension creation worked! I wonder if this is a java bug? 
```
# ls -lsrt /usr/lib/jvm/default-jvm/lib/libj*
   188 -rw-r--r--    1 root     root        189984 Apr 18  2021 /usr/lib/jvm/default-jvm/lib/libjava.so
     0 lrwxrwxrwx    1 root     root            45 Dec 17 18:59 /usr/lib/jvm/default-jvm/lib/libjvm.so -> /usr/lib/jvm/default-jvm/lib/server/libjvm.so
```

**Comment by jcflack** [comment]
Good find! To me it sounds like something wonky in the way your particular distro is building/packaging Java.

At the moment, I have a dozen different Java versions untarred all in different directories in `/var/tmp`, and I can build PL/Java one time and run it in the same database with any one of them, just with different `SET pljava.libjvm_location TO ...` commands:

```
postgres=# \t
Tuples only is on.
postgres=# select javatest.java_getsystemproperty('java.vm.version');
 17+35

postgres=# \c
You are now connected to database "postgres" as user "nobody".
postgres=# set pljava.libjvm_location to '/var/tmp/jdk-9.0.4+11/lib/server/libjvm.so';
SET
postgres=# select javatest.java_getsystemproperty('java.vm.version');
 9.0.4+11

postgres=# \c
You are now connected to database "postgres" as user "nobody".
postgres=# set pljava.libjvm_location to '/var/tmp/jdk-10.0.2+13/lib/server/libjvm.so';
SET
postgres=# select javatest.java_getsystemproperty('java.vm.version');
 10.0.2+13

postgres=# \c
You are now connected to database "postgres" as user "nobody".
postgres=# set pljava.libjvm_location to '/var/tmp/jdk-11.0.12+7j9/lib/server/libjvm.so';
SET
postgres=# select javatest.java_getsystemproperty('java.vm.version');
 openj9-0.27.0

postgres=# \c
You are now connected to database "postgres" as user "nobody".
postgres=# set pljava.libjvm_location to '/var/tmp/jdk-11.0.12+7/lib/server/libjvm.so';
SET
postgres=# select javatest.java_getsystemproperty('java.vm.version');
 11.0.12+7

postgres=# \c
You are now connected to database "postgres" as user "nobody".
postgres=# set pljava.libjvm_location to '/var/tmp/graalvm-ce-java11-21.2.0/lib/server/libjvm.so';
SET
postgres=# select javatest.java_getsystemproperty('java.vm.version');
 11.0.12+6-jvmci-21.2-b08
```
That's the way it should go when things work right. None of the Java versions have any trouble finding themselves, starting with the `libjvm.so` file that PL/Java loads them from. No extra environment variables or symlinks *should* be needed.

> I tried with java 10 and it gave the same exact error. Enabling the debug logging also didn't show anything new/helpful.

Would you be able to include the log output anyway? Do your PostgreSQL settings include `logging_collector = on` ?

There are probably some exotic `-XX:` options for `java` that could be added in `pljava.vmoptions` and cause Java to log more information about how it is locating libraries. I would have to look those up; they are not familiar to me offhand. There is also `strace`.

It might be worthwhile to find the contact info for the maintainers of those Java packages and bring them into the conversation; maybe refer them to this issue. They might have some ideas how to debug what is confusing the packages.

**Comment by jcflack** [comment]
> You might get some useful information with `SET log_min_messages TO debug2` in PostgreSQL before loading PL/Java.

It slipped my mind that when you use the PostgreSQL `CREATE EXTENSION` command, it changes the logging level for the duration of the command, which has the effect of suppressing any messages you might have wanted if you had set a finer level.

There is an alternative way to load PL/Java, from back before PostgreSQL had `CREATE EXTENSION`:

```
LOAD 'libpljava-so-1.6.3';
```

that does not suppress the logging.

**Comment by udesaiitrs** [comment]
Yeah I'll have to investigate deeper next week, and I can get you some of that info you asked for. I was able to at least move forward and run some custom functions to test the viability of this for what we're trying to do! 

I did also try the `LOAD ...` method, but it throws the same exact error, so I think that the issue is certainly with java and maybe some path errors? I'll dig into it next week for sure and follow up, thanks for the help so far.

**Comment by jcflack** [comment]
Right, I wasn't expecting `LOAD` to give a different outcome than `CREATE EXTENSION`.

It's just that if you are trying to get debug information, and you `SET log_min_messages TO debug2;` or the like, `CREATE EXTENSION` kills that setting while it operates, so you don't get the debug info. (Somebody must have thought the quieter output is nice, but I can't say how many times I've repeated the "wait! where's my debug output?! oh, yeah, `CREATE EXTENSION` killed it" act.)

`LOAD` does not kill that setting, so you can get better debug information during the startup.

**Comment by udesaiitrs** [comment]
Hi thanks for you help on this, going to close the issue for now. We are going with a different base image and no issues there!
