### ISSUE TITLE
Spring support

### ISSUE THREAD

**Issue by gjevardat** [tada/pljava#384]
Hello
I'am not sure if there are specific settings to enable Spring context Annotation  in a deployed pljava code.

In my example, the context is starting well and find the technical internal spring beans. But it fails finding the beans I have defined ! This code works well in a separate module or when I run it in a static main method!

Here is the example code

```
public class OperatorFacade {

	static ApplicationContext context;
	static OperatorChain chain;

	public static boolean cleanTimeseries(long sourceid, String operatorName, ResultSet receiver)
			throws SQLException, IOException, ClassNotFoundException {

		try {
			Logger.getAnonymousLogger().info("Starting Operator module");
			context = new AnnotationConfigApplicationContext("roopackage");
			String[] beanDefinitionNames = context.getBeanDefinitionNames();
			for (int i = 0; i < beanDefinitionNames.length; i++) {
				Logger.getAnonymousLogger().info(beanDefinitionNames[i]);
			}
			chain = context.getBean(OperatorChain.class);
			chain.initFromFile("operatorchain-test.xml");
			
		} catch (Exception e) {
			Logger.getAnonymousLogger(e.getMessage());
		}
               ....

		return true;
	}
```
PS: I removed lazy initialisation code for clarity. The context will be only started and initialized once !
Any help is welcome thanks !

**Comment by gjevardat** [comment]
I have found a workaround by initialising the application context providing directly all the bean classes. Not sure why package based init is failing tough.

**Comment by jcflack** [comment]
Hi,

Could you include the version of PL/Java and maybe an exception message and/or stack trace from the failure?

`SET client_min_messages TO debug1` (or `SET log_min_messages TO debug1`) will add stack traces for Java exceptions (in many, if not all, cases).

**Comment by gjevardat** [comment]
Sorry for late answer, for now the workaround is ok on my side and I'am fighting with new issue :)
