### ISSUE TITLE
PostgreSQL 15 support

### ISSUE THREAD

**Issue by yevon** [tada/pljava#410]
Is postgresql 15 supported? What should I change in order to being able to use pljava with the postgres 15 beta?

**Comment by aadrian** [comment]
Any information on this?

Thank you.

**Comment by tran4o** [comment]
I have pg 15 working fork, in the fork are some extra functionalities you can ignore. Maybe you need to just to copy the native code where String is refactored as StringPL

**Comment by jcflack** [comment]
Believed resolved in 1.6.5.
