### ISSUE TITLE
Access Denied - java.io.FilePermission

### ISSUE THREAD

**Issue by SreevidyaAravind1989** [tada/pljava#417]
Issue exists while trying to call a DB function that calls a java function by reading the file name.
Getting the Following error.
SQL Error [42501]: ERROR: java.sql.SQLSyntaxErrorException: access denied ("java.io.FilePermission" "/path/fileName.txt" "read")

pljava version used: 2-SNAPSHOT
java version :11.0.17
postgres version:13

Added the following to pljava.policy file

grant principal org.postgresql.pljava.PLPrincipal$Sandboxed "java" {
};

grant principal org.postgresql.pljava.PLPrincipal$Unsandboxed "javaU" {
    permission java.io.FilePermission
        "<<ALL FILES>>", "read,readlink,write,delete";
};
grant codebase "sqlj:testapp" {
    permission java.util.PropertyPermission "user.timezone", "write";
};
grant {
    permission java.util.PropertyPermission
        "sqlj.defaultconnection", "read";
};
grant {
  permission java.security.AllPermission;
};

**Comment by jcflack** [comment]
Would you be able to attach the log output from executing your DB function with PL/Java's `TrialPolicy` enabled, as described [here][tp]?

[tp]: https://tada.github.io/pljava/use/trial.html#Configuring_a_trial_policy

**Comment by jcflack** [comment]
Closed waiting on reporter
