### ISSUE TITLE
Help demonstration example I can't use

### ISSUE THREAD

**Issue by exqmjmz** [tada/pljava#421]
Demonstration example I can't use
I tried different methods
Prompt the following error
example:ResultSetTest.java

<pre>
CREATE OR REPLACE FUNCTION test_pljava(query TEXT) RETURNS TEXT AS 'com.kamin.pljava.Cases.executeSelect' LANGUAGE java
> ERROR:  java.sql.SQLNonTransientException: resolving static method com.kamin.pljava.Cases.executeSelect with signature (String)String: java.lang.NoSuchMethodException: no such method: com.kamin.pljava.Cases.executeSelect(String)String/invokeStatic
</pre>

<pre>
CREATE OR REPLACE FUNCTION test_pljava(query TEXT) RETURNS SETOF mv_case_template AS 'com.kamin.pljava.Cases.executeSelect' LANGUAGE java
> ERROR:  java.sql.SQLNonTransientException: resolving static method com.kamin.pljava.Cases.executeSelect with signature (String)ResultSetProvider: java.lang.NoSuchMethodException: no such method: com.kamin.pljava.Cases.executeSelect(String)ResultSetProvider/invokeStatic
</pre>

**Comment by jcflack** [comment]
Hi,

Can you include the output of the following?

```sql
SELECT schemaname, jarname
  FROM sqlj.classpath_entry NATURAL JOIN sqlj.jar_repository
  ORDER BY schemaname, ordinal;

SHOW pljava.classpath;
SHOW search_path;
```

Very often, an issue like what you are reporting will have an explanation among those settings.

**Comment by ljm000** [comment]
> ```sql
> SELECT schemaname, jarname
>   FROM sqlj.classpath_entry NATURAL JOIN sqlj.jar_repository
>   ORDER BY schemaname, ordinal;
> 
> SHOW pljava.classpath;
> SHOW search_path;
> ```

**SELECT schemaname, jarname
  FROM sqlj.classpath_entry NATURAL JOIN sqlj.jar_repository
  ORDER BY schemaname, ordinal;**
return:

schemaname	jarname
public	        pgjar

**SHOW pljava.classpath;**
return:

ERROR:  unrecognized configuration parameter "pljava.classpath"

**SHOW search_path;**
return:

search_path
public, "$user", public

**Comment by jcflack** [comment]
Oops, sorry, I copied the `show pljava.classpath` from an older issue, before the variable name changed. It would be `show pljava.module_path` in recent versions.

But even that might be less important here than

```sql
SELECT sqlj.get_classpath('public');
```

**Comment by ljm000** [comment]
> Oops, sorry, I copied the `show pljava.classpath` from an older issue, before the variable name changed. It would be `show pljava.module_path` in recent versions.
> 
> But even that might be less important here than
> 
> ```sql
> SELECT sqlj.get_classpath('public');
> ```

It's all right, glad you helped!
return:

get_classpath
pgjar

**Comment by jcflack** [comment]
This may show more:

```sql
\c
SET client_min_messages TO debug1;
CREATE OR REPLACE FUNCTION test_pljava(query TEXT) RETURNS TEXT AS 'com.kamin.pljava.Cases.executeSelect' LANGUAGE java;
```

Sometimes during create-time validation, another exception further down the stacktrace may end up looking like the method wasn't found.

If you don't see more useful output at the client, also take a look in the server log afterward.

**Comment by jcflack** [comment]
Was there any resolution?

**Comment by jcflack** [comment]
Closed waiting on reporter
