### ISSUE TITLE
Compilen error occuring while running mvn clean install

### ISSUE THREAD

**Issue by NehaAnthony** [tada/pljava#473]
while running in order to solve import issue for the code and dependency.mvn clean install is throughing error and also in order to solve the a nre error arise where all imports are greyed out and red.
 the following is error-
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[1,47] package software.amazon.awssdk.auth.credentials does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[2,47] package software.amazon.awssdk.auth.credentials does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[3,47] package software.amazon.awssdk.auth.credentials does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[4,38] package software.amazon.awssdk.regions does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[6,48] package software.amazon.awssdk.services.textract does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[9,54] package software.amazon.awssdk.services.textract.model does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[11,54] package software.amazon.awssdk.services.textract.model does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[57,45] cannot find symbol
  symbol:   class TextractClient
  location: class cell
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[93,41] cannot find symbol
  symbol:   class TextractClient
  location: class cell
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[133,55] cannot find symbol
  symbol:   class Block
  location: class cell
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[144,37] cannot find symbol
  symbol:   class Block
  location: class cell
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[144,60] cannot find symbol
  symbol:   class Block
  location: class cell
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[157,49] cannot find symbol
  symbol:   class Block
  location: class cell
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[157,24] cannot find symbol
  symbol:   class Block
  location: class cell
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/cell.java:[5,1] package software.amazon.awssdk.services.textract.model does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[1,47] package software.amazon.awssdk.auth.credentials does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[2,47] package software.amazon.awssdk.auth.credentials does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[3,38] package software.amazon.awssdk.regions does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[5,48] package software.amazon.awssdk.services.textract does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[7,54] package software.amazon.awssdk.services.textract.model does not exist
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[52,47] cannot find symbol
  symbol:   class TextractClient
  location: class textract
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[90,41] cannot find symbol
  symbol:   class TextractClient
  location: class textract
[ERROR] /C:/Users/Hp/AppData/Local/Temp/Temp057c41d7-73c5-496a-a06a-b173ed3e0be0_maven-shade-plugin-3.5.1-source-release (1).zip/JC/src/main/java/textract.java:[126,56] cannot find symbol
  symbol:   class Block
  location: class textract

**Comment by jcflack** [comment]
This does not appear to be a report about building PL/Java itself ... the source files and packages shown in the report are nothing used in PL/Java. The `maven-shade-plugin` appears to be involved, which is not even used when I build PL/Java locally (there is no `maven-shade-plugin` in the local Maven repository after a successful PL/Java build).

If this is happening in a build of user code _to be used with_ PL/Java, the chief problem would seem to be to find why the `software.amazon.awssdk...` packages are not being found.

**Comment by NehaAnthony** [comment]
I had already solved the issue

Thanks
