### ISSUE TITLE
fatal error: postgres.h: No such file or directory

### ISSUE THREAD

**Issue by emdao** [tada/pljava#477]
we are compiling pljva with the following command

mvn clean install

But we are getting the following error

var/lib/pgsql/pljava/pljava-so/src/main/c/Backend.c:14:10: fatal error: postgres.h: No such file or directory
   14 | #include <postgres.h>
      |          ^~~~~~~~~~~~
compilation terminated.
In file included from /var/lib/pgsql/pljava/pljava-so/src/main/c/DualState.c:21:
/var/lib/pgsql/pljava/pljava-so/src/main/include/pljava/DualState.h:15:10: fatal error: postgres.h: No such file or directory
   15 | #include <postgres.h>
      |          ^~~~~~~~~~~~
compilation terminated.
/var/lib/pgsql/pljava/pljava-so/src/main/c/Exception.c:15:10: fatal error: postgres.h: No such file or directory
   15 | #include <postgres.h>
      |          ^~~~~~~~~~~~
compilation terminated.
/var/lib/pgsql/pljava/pljava-so/src/main/c/ExecutionPlan.c:15:10: fatal error: postgres.h: No such file or directory
   15 | #include <postgres.h>
      |          ^~~~~~~~~~~~

we have installed postgres version 15 and our operating system is redhat linux version 9.

Postgres version obtained from redhat nis not the development version.

**Comment by jcflack** [comment]
Closed waiting on reporter ... looks like a simple case of not having PostgreSQL dev package installed.
