### ISSUE TITLE
Support PostgreSQL 9.5

### ISSUE THREAD

**Issue by mc-soi** [tada/pljava#48]
This patch adds support for PostgreSQL 9.5 by adding a required parameter:
https://gist.github.com/mc-soi/34d980feeb92f8208dfb

A #if (PG_VERSION_NUM >= 90500) might be needed to make this code also compile with earlier versions.

**Comment by jcflack** [comment]
Hi,

Thank you very much for the patch! I know it is small, but would it be possible for you to complete the patch with version test as you describe, then submit a pull request? The [contribution guide][cguide] explains the preferred practices around here.

If you browse some of the code, or the `pljava-so/pom.xml`, you'll see that `PG_VERSION_NUM` isn't usually the definition that's tested, even though it is available. A test like

    #if (PGSQL_MAJOR_VER > 9 || (PGSQL_MAJOR_VER == 9 && PGSQL_MINOR_VER >= 5))

would be maintain consistency with the rest of the code. The comment with your commit will be most useful if it even briefly mentions what the new parameter is for, why `false` is the right value, etc., just so anyone reading the history and seeing what you changed will not have to look those details up in the PostgreSQL sources to understand them.

Thanks!
-Chap

[cguide]: https://github.com/tada/pljava/wiki/Contribution-guide
