### ISSUE TITLE
I meet a compile error while compiling PL/Java using maven

### ISSUE THREAD

**Issue by shenjianrong** [tada/pljava#493]
I meet a compile error as following while compiling PL/Java using "mvn clean install" command, how to resolve this problem?

/home/sjr/pljava-master/pljava-so/src/main/c/Backend.c:26:27: 致命错误：utils/timeout.h：没有那个文件或目录
 #include <utils/timeout.h>
                           ^
编译中断。
In file included from /home/sjr/pljava-master/pljava-so/src/main/include/pljava/DualState.h:18:0,
                 from /home/sjr/pljava-master/pljava-so/src/main/c/DualState.c:21:
/home/sjr/pljava-master/pljava-so/src/main/include/pljava/pljava.h:40:33: 致命错误：access/htup_details.h：没有那个文件或目录
 #include <access/htup_details.h>
                                 ^
编译中断。
In file included from /home/sjr/pljava-master/pljava-so/src/main/include/pljava/JNICalls.h:18:0,
                 from /home/sjr/pljava-master/pljava-so/src/main/include/pljava/PgObject.h:16,
                 from /home/sjr/pljava-master/pljava-so/src/main/include/pljava/type/Type.h:16,
                 from /home/sjr/pljava-master/pljava-so/src/main/include/pljava/Function.h:16,
                 from /home/sjr/pljava-master/pljava-so/src/main/include/pljava/Backend.h:17,
                 from /home/sjr/pljava-master/pljava-so/src/main/c/Exception.c:18:
/home/sjr/pljava-master/pljava-so/src/main/include/pljava/pljava.h:40:33: 致命错误：access/htup_details.h：没有那个文件或目录
 #include <access/htup_details.h>
                                 ^
编译中断。

**Comment by jcflack** [comment]
It may be helpful if you can post the output of the `pg_config` command (the same one found on the search path by the Maven build).

One of the paths output by `pg_config` will be `INCLUDEDIR_SERVER`. Can you check on that path for the existence of `utils/timeout.h` and `access/htup_details.h` files?

**Comment by shenjianrong** [comment]
Thanks for your replying.
The pg_config command is:
BINDIR = /usr/bin
DOCDIR = /usr/share/doc/pgsql
HTMLDIR = /usr/share/doc/pgsql
INCLUDEDIR = /usr/include
PKGINCLUDEDIR = /usr/include/pgsql
INCLUDEDIR-SERVER = /usr/include/pgsql/server
......
VERSION = PostgreSQL 15.7

My computer’s OS is CentOS 7, I can’t find the install package of PostgreSQL 16.

The following pictures are files in /usr/include/pgsql/server/access and /usr/include/pgsql/server/utils directory.
![access](https://github.com/tada/pljava/assets/94516085/d1f2668c-1c6c-4aa2-94ca-68cb0962ce25)
![utils](https://github.com/tada/pljava/assets/94516085/34911414-e306-4294-a143-c39c14d04662)
I have tried PL/Java version 1.6.6 and 1.6.7.
When I try the PL/Java version 1.6.2 to 1.6.5, another compile error occur like following picture.
![PLJava1 6 5_error](https://github.com/tada/pljava/assets/94516085/54df6e51-0dc3-473b-9487-c3f010ef1cd3)

**Comment by jcflack** [comment]
If `pg_config` reports version 15.7, you should definitely have [`access/htup_details.h`][htup_details.h] and [`utils/timeout.h`][timeout.h]. It appears that somehow the PostgreSQL development package installed on your system may be incomplete, or somehow does not correspond to the reported version.

I cannot say how to remedy that, but this should give you something to investigate.

PL/Java's [release notes][rn] indicate that PostgreSQL 15 support was added in PL/Java 1.6.5. So I am not surprised that another compilation error is encountered with 1.6.2 through 1.6.4. I _am_ surprised about an error with 1.6.5, but again, I don't have a complete understanding of exactly what parts of what versions of PostgreSQL are installed on your system.

[htup_details.h]: https://github.com/postgres/postgres/blob/4a53584cf2d676e685d899d01cde18c075fbeca7/src/include/access/htup_details.h
[timeout.h]: https://github.com/postgres/postgres/blob/4a53584cf2d676e685d899d01cde18c075fbeca7/src/include/utils/timeout.h
[rn]: https://tada.github.io/pljava/releasenotes.html

**Comment by shenjianrong** [comment]
I have installed

**Comment by jcflack** [comment]
Does the repository you are installing from have a package `postgresql15-server-devel`?

**Comment by shenjianrong** [comment]
[root@localhost bin]# sudo yum install postgresql15-devel
已加载插件：fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: mirrors.aliyun.com
 * epel: mirrors.aliyun.com
 * extras: mirrors.aliyun.com
 * updates: mirrors.aliyun.com
正在解决依赖关系
--> 正在检查事务
---> 软件包 postgresql15-devel.x86_64.0.15.7-1PGDG.rhel7 将被 安装
--> 正在处理依赖关系 llvm5.0-devel >= 5.0，它被软件包 postgresql15-devel-15.7-1PGDG.rhel7.x86_64 需要
--> 正在处理依赖关系 llvm-toolset-7-clang >= 4.0.1，它被软件包 postgresql15-devel-15.7-1PGDG.rhel7.x86_64 需要
--> 正在处理依赖关系 perl(IPC::Run)，它被软件包 postgresql15-devel-15.7-1PGDG.rhel7.x86_64 需要
--> 正在检查事务
---> 软件包 llvm5.0-devel.x86_64.0.5.0.1-7.el7 将被 安装
--> 正在处理依赖关系 llvm5.0(x86-64) = 5.0.1-7.el7，它被软件包 llvm5.0-devel-5.0.1-7.el7.x86_64 需要
--> 正在处理依赖关系 libedit-devel，它被软件包 llvm5.0-devel-5.0.1-7.el7.x86_64 需要
--> 正在处理依赖关系 libLLVM-5.0.so()(64bit)，它被软件包 llvm5.0-devel-5.0.1-7.el7.x86_64 需要
--> 正在处理依赖关系 libLTO.so.5()(64bit)，它被软件包 llvm5.0-devel-5.0.1-7.el7.x86_64 需要
---> 软件包 perl-IPC-Run.noarch.0.0.92-2.el7 将被 安装
--> 正在处理依赖关系 perl(IO::Pty) >= 1.08，它被软件包 perl-IPC-Run-0.92-2.el7.noarch 需要
---> 软件包 postgresql15-devel.x86_64.0.15.7-1PGDG.rhel7 将被 安装
--> 正在处理依赖关系 llvm-toolset-7-clang >= 4.0.1，它被软件包 postgresql15-devel-15.7-1PGDG.rhel7.x86_64 需要
--> 正在检查事务
---> 软件包 libedit-devel.x86_64.0.3.0-12.20121213cvs.el7 将被 安装
---> 软件包 llvm5.0.x86_64.0.5.0.1-7.el7 将被 安装
---> 软件包 llvm5.0-libs.x86_64.0.5.0.1-7.el7 将被 安装
---> 软件包 perl-IO-Tty.x86_64.0.1.10-11.el7 将被 安装
---> 软件包 postgresql15-devel.x86_64.0.15.7-1PGDG.rhel7 将被 安装
--> 正在处理依赖关系 llvm-toolset-7-clang >= 4.0.1，它被软件包 postgresql15-devel-15.7-1PGDG.rhel7.x86_64 需要
--> 解决依赖关系完成
错误：软件包：postgresql15-devel-15.7-1PGDG.rhel7.x86_64 (pgdg15)
          需要：llvm-toolset-7-clang >= 4.0.1

**Comment by jcflack** [comment]
I assume that the `yum install postgresql15-devel` shown in your 1 July comment resolved the issue. Please feel free to reopen with additional information if it did not.
