### ISSUE TITLE
nexus.tada.se painfully slow

### ISSUE THREAD

**Issue by yazun** [tada/pljava#62]
It takes hours to build sometimes because of this:
loading: http://nexus.tada.se/content/repositories/releases/org/apache/maven/plugins/maven-install-plugin/maven-metadata.xml
Downloading: http://nexus.tada.se/content/repositories/snapshots/org/apache/maven/plugins/maven-install-plugin/maven-metadata.xml
[WARNING] Could not transfer metadata org.apache.maven.plugins:maven-install-plugin/maven-metadata.xml from/to releases.tada.se (http://nexus.tada.se/content/repositories/releases/): Failed to transfer f.
[WARNING] Could not transfer metadata org.apache.maven.plugins:maven-install-plugin/maven-metadata.xml from/to snapshots.tada.se (http://nexus.tada.se/content/repositories/snapshots/): Failed to transfer.
Downloading: ht

**Comment by jcflack** [comment]
My apologies ... there is an open pull request (#60) to fix that, I forgot it hadn't been merged yet. Meanwhile, you can use that version of pom.xml, it builds a lot faster. :)

**Comment by yazun** [comment]
Thanks, 
I used mvn -o and it helped after the first download.
