### ISSUE TITLE
mvn compile fails

### ISSUE THREAD

**Issue by yolile** [tada/pljava#84]
Im trying to install pljava, when I clone de the repo and execute mvn compile, its fails cause a maven nar plugin problem, the important part of stack trace:
Caused by: org.apache.maven.plugin.MojoFailureException: NAR: Include path not found: com.github.maven_nar.IncludePath@6f94fb9d
	at com.github.maven_nar.Compiler.getCompiler(Compiler.java:592)

My maven version is 3.0.5, java 8 and postgresql 9.3, in Ubuntu 14.04 64 bits

**Comment by jcflack** [comment]
Hi,

Thanks for the report! This seems to be failing at a place where
the nar-maven-plugin checks that the specified include paths are
real directories that exist on your system:

https://github.com/maven-nar/nar-maven-plugin/blob/7ba6ca9f3fc4385d360a8f326d20322cea1118a8/src/main/java/com/github/maven_nar/Compiler.java#L592

Sadly, nar's IncludePath class doesn't have its own toString() method,
so when the error message prints it out, we don't see what include path
wasn't found, but only the address of the object. :(

Still, on Ubuntu you probably only have the paths set in the main part
of the pljava.so pom.xml:

https://github.com/tada/pljava/blob/29829e1c7ab7fa94570d1567f8400dc04de5f8b0/pljava-so/pom.xml#L201

So, the first thing I would check ... run pg_config and look for the
INCLUDEDIR and INCLUDEDIR-SERVER lines, then check that both of those
directories exist on your system and have a bunch of *.h files in them.

Perhaps on Ubuntu there is a postgresql -devel package that you have
not installed yet?

Regards,
-Chap

**Comment by jcflack** [comment]
> Sadly, nar's IncludePath class doesn't have its own toString() method,
> so when the error message prints it out, we don't see what include path
> wasn't found, but only the address of the object. :(

I've reported that part to the nar folks at maven-nar/nar-maven-plugin#204.

-Chap

**Comment by yolile** [comment]
Thank you, you are right, I didn't have the postgresql-server-dev-9.3, libkrb5-dev and libecpg-dev packets, after install those, the project finally compiled!
